#import "LoginFormDetector.h"
#import "LoginAssistScriptMessageProxy.h"
#import "LoginAssistPreferences.h"

NSString * const LoginFormInlineHandlerName = @"loginFormInline";

@implementation LoginFormDetector

+ (void)installOnConfiguration:(WKWebViewConfiguration *)configuration
               messageHandler:(id<WKScriptMessageHandler>)handler {
    if (!configuration || !handler) {
        return;
    }

    WKUserContentController *ucc = configuration.userContentController;
    if (!ucc) {
        ucc = [[WKUserContentController alloc] init];
        configuration.userContentController = ucc;
    }

    [ucc removeScriptMessageHandlerForName:LoginFormInlineHandlerName];
    LoginAssistScriptMessageProxy *proxy = [[LoginAssistScriptMessageProxy alloc] init];
    proxy.target = handler;
    [ucc addScriptMessageHandler:proxy name:LoginFormInlineHandlerName];

    // 新标签使用当前 Pref；已打开页需重启窗口或导航刷新脚本时机有限。
    BOOL enabled = [LoginAssistPreferences inlineAssistEnabled];
    NSString *source = [NSString stringWithFormat:@"window.__meoLoginInlineEnabled=%@;\n%@",
                        enabled ? @"true" : @"false",
                        [self userScriptSource]];
    WKUserScript *script = [[WKUserScript alloc] initWithSource:source
                                                  injectionTime:WKUserScriptInjectionTimeAtDocumentEnd
                                               forMainFrameOnly:YES];
    [ucc addUserScript:script];
}

+ (NSString *)userScriptSource {
    return @
"(function() {\n"
"  if (window.__meoLoginFormInlineInstalled) { return; }\n"
"  if (window.__meoLoginInlineEnabled === false) { return; }\n"
"  window.__meoLoginFormInlineInstalled = true;\n"
"  const HANDLER = 'loginFormInline';\n"
"  const BTN_ATTR = 'data-meo-login-assist';\n"
"  let debounceTimer = null;\n"
"  let activeFormId = null;\n"
"  const drafts = {};\n"
"\n"
"  function post(payload) {\n"
"    try { window.webkit.messageHandlers[HANDLER].postMessage(payload); } catch (e) {}\n"
"  }\n"
"  function visible(el) {\n"
"    if (!el || el.disabled) return false;\n"
"    const st = window.getComputedStyle(el);\n"
"    if (st.display === 'none' || st.visibility === 'hidden' || st.opacity === '0') return false;\n"
"    const r = el.getBoundingClientRect();\n"
"    return r.width > 0 && r.height > 0;\n"
"  }\n"
"  function textBlob(el) {\n"
"    return [el.name, el.id, el.placeholder, el.getAttribute('aria-label'), el.autocomplete]\n"
"      .filter(Boolean).join(' ').toLowerCase();\n"
"  }\n"
"  function isAccountField(el) {\n"
"    if (!el || el.tagName !== 'INPUT' || !visible(el)) return false;\n"
"    const t = (el.type || 'text').toLowerCase();\n"
"    if (t === 'password' || t === 'hidden' || t === 'submit' || t === 'button' || t === 'checkbox' || t === 'radio' || t === 'search' || t === 'file') return false;\n"
"    if (t === 'email' || t === 'tel') return true;\n"
"    if (t !== 'text' && t !== '') return false;\n"
"    const ac = (el.autocomplete || '').toLowerCase();\n"
"    if (/(username|email|tel|nickname|name)/.test(ac)) return true;\n"
"    return /(user|login|account|email|mail|手机|帐号|账号|邮箱|phone)/i.test(textBlob(el));\n"
"  }\n"
"  function isPasswordField(el) {\n"
"    if (!el || el.tagName !== 'INPUT' || !visible(el)) return false;\n"
"    const t = (el.type || '').toLowerCase();\n"
"    if (t === 'password') return true;\n"
"    const ac = (el.autocomplete || '').toLowerCase();\n"
"    return ac.indexOf('current-password') >= 0 || ac.indexOf('new-password') >= 0;\n"
"  }\n"
"  function isOTPField(el) {\n"
"    if (!el || el.tagName !== 'INPUT' || !visible(el)) return false;\n"
"    const ac = (el.autocomplete || '').toLowerCase();\n"
"    if (ac.indexOf('one-time-code') >= 0) return true;\n"
"    return /(otp|code|验证码|校验码|auth.?code)/i.test(textBlob(el));\n"
"  }\n"
"  function isRegisterish(root) {\n"
"    const pw = Array.from(root.querySelectorAll('input')).filter(isPasswordField);\n"
"    if (pw.length < 2) return false;\n"
"    return pw.some(p => ((p.autocomplete || '').toLowerCase().indexOf('new-password') >= 0));\n"
"  }\n"
"  function cssPath(el) {\n"
"    if (!el || el.nodeType !== 1) return '';\n"
"    function esc(v) {\n"
"      if (window.CSS && CSS.escape) return CSS.escape(v);\n"
"      return String(v).replace(/[^a-zA-Z0-9_-]/g, '\\\\$&');\n"
"    }\n"
"    if (el.id) {\n"
"      const s = '#' + esc(el.id);\n"
"      try { if (document.querySelectorAll(s).length === 1) return s; } catch (e) {}\n"
"    }\n"
"    const name = el.getAttribute('name');\n"
"    if (name) {\n"
"      const s = el.tagName.toLowerCase() + '[name=\"' + name.replace(/\"/g, '\\\\\"') + '\"]';\n"
"      try { if (document.querySelectorAll(s).length === 1) return s; } catch (e) {}\n"
"    }\n"
"    const parts = [];\n"
"    let node = el;\n"
"    while (node && node.nodeType === 1 && node !== document.body && parts.length < 5) {\n"
"      let part = node.tagName.toLowerCase();\n"
"      const parent = node.parentElement;\n"
"      if (parent) {\n"
"        const siblings = Array.from(parent.children).filter(c => c.tagName === node.tagName);\n"
"        if (siblings.length > 1) part += ':nth-of-type(' + (siblings.indexOf(node) + 1) + ')';\n"
"      }\n"
"      parts.unshift(part);\n"
"      node = parent;\n"
"    }\n"
"    return parts.join(' > ');\n"
"  }\n"
"  function findSubmit(root, passEl) {\n"
"    let btn = root.querySelector('button[type=\"submit\"], input[type=\"submit\"]');\n"
"    if (btn && visible(btn)) return btn;\n"
"    const buttons = Array.from(root.querySelectorAll('button, input[type=\"button\"]')).filter(visible);\n"
"    const hit = buttons.find(b => /(log\\s*in|sign\\s*in|登录|登陸|提交|signin)/i.test((b.textContent || b.value || '') + ' ' + textBlob(b)));\n"
"    return hit || null;\n"
"  }\n"
"  function contexts() {\n"
"    const results = [];\n"
"    const forms = Array.from(document.querySelectorAll('form'));\n"
"    const roots = forms.length ? forms : [document.body];\n"
"    roots.forEach((root, idx) => {\n"
"      if (!root || isRegisterish(root)) return;\n"
"      const inputs = Array.from(root.querySelectorAll('input'));\n"
"      const pass = inputs.find(isPasswordField);\n"
"      if (!pass) return;\n"
"      const user = inputs.find(el => isAccountField(el));\n"
"      if (!user) return;\n"
"      const otp = inputs.some(isOTPField);\n"
"      const submit = findSubmit(root, pass);\n"
"      const formId = root.id ? ('id:' + root.id) : ('auto:' + idx + ':' + cssPath(pass));\n"
"      results.push({ root, user, pass, submit, otp, formId });\n"
"    });\n"
"    if (!results.length && document.body) {\n"
"      const inputs = Array.from(document.querySelectorAll('input'));\n"
"      const pass = inputs.find(isPasswordField);\n"
"      const user = inputs.find(isAccountField);\n"
"      if (pass && user && !isRegisterish(document.body)) {\n"
"        results.push({\n"
"          root: document.body,\n"
"          user, pass,\n"
"          submit: findSubmit(document.body, pass),\n"
"          otp: inputs.some(isOTPField),\n"
"          formId: 'body:' + cssPath(pass)\n"
"        });\n"
"      }\n"
"    }\n"
"    return results;\n"
"  }\n"
"  function ensureStyle() {\n"
"    if (document.getElementById('meo-login-assist-style')) return;\n"
"    const style = document.createElement('style');\n"
"    style.id = 'meo-login-assist-style';\n"
"    style.textContent = '' +\n"
"      'input[' + BTN_ATTR + '-host=\"1\"]{ padding-right: 28px !important; }' +\n"
"      'button.meo-login-assist-btn{' +\n"
"      'position:absolute;z-index:2147483646;width:20px;height:20px;border:0;padding:0;' +\n"
"      'border-radius:4px;cursor:pointer;background:rgba(128,128,128,0.18);' +\n"
"      'color:inherit;font-size:12px;line-height:20px;text-align:center;' +\n"
"      '}' +\n"
"      'button.meo-login-assist-btn:hover{background:rgba(10,132,255,0.25);}';\n"
"    document.documentElement.appendChild(style);\n"
"  }\n"
"  function placeButton(ctx) {\n"
"    ensureStyle();\n"
"    const pass = ctx.pass;\n"
"    pass.setAttribute(BTN_ATTR + '-host', '1');\n"
"    let btn = document.querySelector('button.meo-login-assist-btn[' + BTN_ATTR + '=\"' + String(ctx.formId).replace(/\\\\/g,'\\\\\\\\').replace(/\"/g,'\\\\\"') + '\"]');\n"
"    if (!btn) {\n"
"      btn = document.createElement('button');\n"
"      btn.type = 'button';\n"
"      btn.className = 'meo-login-assist-btn';\n"
"      btn.setAttribute(BTN_ATTR, ctx.formId);\n"
"      btn.setAttribute('aria-label', '登录助手');\n"
"      btn.title = '登录助手';\n"
"      btn.textContent = '\\uD83D\\uDD11';\n"
"      btn.addEventListener('click', function(e) {\n"
"        e.preventDefault(); e.stopPropagation();\n"
"        const r = btn.getBoundingClientRect();\n"
"        post({\n"
"          type: 'iconClicked',\n"
"          formId: ctx.formId,\n"
"          hasOTP: !!ctx.otp,\n"
"          usernameSelector: cssPath(ctx.user),\n"
"          passwordSelector: cssPath(ctx.pass),\n"
"          submitSelector: ctx.submit ? cssPath(ctx.submit) : '',\n"
"          left: r.left, top: r.top, width: r.width, height: r.height,\n"
"          hasUsername: !!(ctx.user && ctx.user.value),\n"
"          hasPassword: !!(ctx.pass && ctx.pass.value)\n"
"        });\n"
"      }, true);\n"
"      document.documentElement.appendChild(btn);\n"
"    }\n"
"    const r = pass.getBoundingClientRect();\n"
"    const top = r.top + window.scrollY + (r.height - 20) / 2;\n"
"    const left = r.left + window.scrollX + r.width - 24;\n"
"    btn.style.top = Math.round(top) + 'px';\n"
"    btn.style.left = Math.round(left) + 'px';\n"
"    btn.style.display = visible(pass) ? 'block' : 'none';\n"
"  }\n"
"  function clearButtons(keepIds) {\n"
"    document.querySelectorAll('button.meo-login-assist-btn').forEach(btn => {\n"
"      const id = btn.getAttribute(BTN_ATTR);\n"
"      if (keepIds && keepIds.has(id)) return;\n"
"      btn.remove();\n"
"    });\n"
"  }\n"
"  function bindDraft(ctx) {\n"
"    if (drafts[ctx.formId]) return;\n"
"    drafts[ctx.formId] = { dirty: false };\n"
"    const mark = function() {\n"
"      const hasU = !!(ctx.user && ctx.user.value);\n"
"      const hasP = !!(ctx.pass && ctx.pass.value);\n"
"      if (hasU && hasP) {\n"
"        drafts[ctx.formId].dirty = true;\n"
"        drafts[ctx.formId].username = ctx.user.value;\n"
"        drafts[ctx.formId].password = ctx.pass.value;\n"
"        drafts[ctx.formId].usernameSelector = cssPath(ctx.user);\n"
"        drafts[ctx.formId].passwordSelector = cssPath(ctx.pass);\n"
"        drafts[ctx.formId].submitSelector = ctx.submit ? cssPath(ctx.submit) : '';\n"
"        drafts[ctx.formId].submitByEnter = !ctx.submit;\n"
"        post({ type: 'credentialsDraft', formId: ctx.formId, hasUsername: true, hasPassword: true });\n"
"      }\n"
"    };\n"
"    ctx.user.addEventListener('input', mark);\n"
"    ctx.pass.addEventListener('input', mark);\n"
"    const root = ctx.root;\n"
"    if (root && root.tagName === 'FORM') {\n"
"      root.addEventListener('submit', function() {\n"
"        mark();\n"
"        if (drafts[ctx.formId] && drafts[ctx.formId].dirty) {\n"
"          drafts[ctx.formId].submittedAt = Date.now();\n"
"          post({ type: 'formSubmitted', formId: ctx.formId });\n"
"        }\n"
"      });\n"
"    }\n"
"  }\n"
"  function scan() {\n"
"    const list = contexts();\n"
"    const ids = new Set(list.map(c => c.formId));\n"
"    clearButtons(ids);\n"
"    if (!list.length) {\n"
"      if (activeFormId) {\n"
"        activeFormId = null;\n"
"        post({ type: 'formCleared' });\n"
"      }\n"
"      return;\n"
"    }\n"
"    list.forEach(ctx => {\n"
"      placeButton(ctx);\n"
"      bindDraft(ctx);\n"
"    });\n"
"    const primary = list[0];\n"
"    activeFormId = primary.formId;\n"
"    post({\n"
"      type: 'formDetected',\n"
"      formId: primary.formId,\n"
"      hasOTP: !!primary.otp,\n"
"      usernameSelector: cssPath(primary.user),\n"
"      passwordSelector: cssPath(primary.pass),\n"
"      submitSelector: primary.submit ? cssPath(primary.submit) : '',\n"
"      formCount: list.length\n"
"    });\n"
"  }\n"
"  function schedule() {\n"
"    if (debounceTimer) clearTimeout(debounceTimer);\n"
"    debounceTimer = setTimeout(scan, 250);\n"
"  }\n"
"  window.__meoLoginAssistFill = function(userSel, passSel, username, password, submitSel, submit) {\n"
"    function qs(sel) { try { return document.querySelector(sel); } catch (e) { return null; } }\n"
"    function setValue(el, value) {\n"
"      if (!el) return;\n"
"      el.focus();\n"
"      const proto = window.HTMLInputElement.prototype;\n"
"      const setter = Object.getOwnPropertyDescriptor(proto, 'value');\n"
"      if (setter && setter.set) setter.set.call(el, value); else el.value = value;\n"
"      el.dispatchEvent(new Event('input', { bubbles: true }));\n"
"      el.dispatchEvent(new Event('change', { bubbles: true }));\n"
"    }\n"
"    setValue(qs(userSel), username || '');\n"
"    setValue(qs(passSel), password || '');\n"
"    if (submit && submitSel) {\n"
"      const btn = qs(submitSel);\n"
"      if (btn) btn.click();\n"
"    }\n"
"    return 'ok';\n"
"  };\n"
"  window.__meoLoginAssistReadDraft = function(formId) {\n"
"    const d = drafts[formId];\n"
"    if (!d || !d.dirty) return null;\n"
"    return {\n"
"      username: d.username || '',\n"
"      password: d.password || '',\n"
"      usernameSelector: d.usernameSelector || '',\n"
"      passwordSelector: d.passwordSelector || '',\n"
"      submitSelector: d.submitSelector || '',\n"
"      submitByEnter: !!d.submitByEnter\n"
"    };\n"
"  };\n"
"  window.__meoLoginAssistConsumeDraftForSave = function() {\n"
"    for (const id in drafts) {\n"
"      if (drafts[id] && drafts[id].dirty) {\n"
"        const d = drafts[id];\n"
"        drafts[id].dirty = false;\n"
"        return {\n"
"          formId: id,\n"
"          username: d.username || '',\n"
"          password: d.password || '',\n"
"          usernameSelector: d.usernameSelector || '',\n"
"          passwordSelector: d.passwordSelector || '',\n"
"          submitSelector: d.submitSelector || '',\n"
"          submitByEnter: !!d.submitByEnter\n"
"        };\n"
"      }\n"
"    }\n"
"    return null;\n"
"  };\n"
"  const mo = new MutationObserver(schedule);\n"
"  mo.observe(document.documentElement, { childList: true, subtree: true });\n"
"  window.addEventListener('resize', schedule);\n"
"  window.addEventListener('scroll', schedule, true);\n"
"  schedule();\n"
"})();";
}

@end
