#import "LoginFormDetector.h"
#import "LoginAssistScriptMessageProxy.h"
#import "LoginAssistPreferences.h"
#import "BrowserRiskHostPolicy.h"
#import "LoginRecipe.h"
#import "LoginCredentialStore.h"

NSString * const LoginFormInlineHandlerName = @"loginFormInline";

@implementation LoginFormDetector

+ (void)installOnConfiguration:(WKWebViewConfiguration *)configuration
               messageHandler:(id<WKScriptMessageHandler>)handler {
    if (!configuration || !handler) {
        return;
    }

    WKUserContentController *ucc = configuration.userContentController;
    if (!ucc) {
        ucc = [[WKUserContentController alloc] init];
        configuration.userContentController = ucc;
    }

    [ucc removeScriptMessageHandlerForName:LoginFormInlineHandlerName];
    LoginAssistScriptMessageProxy *proxy = [[LoginAssistScriptMessageProxy alloc] init];
    proxy.target = handler;
    [ucc addScriptMessageHandler:proxy name:LoginFormInlineHandlerName];

    BOOL enabled = [LoginAssistPreferences inlineAssistEnabled];
    NSString *mode = [LoginAssistPreferences loginFieldInlineMode] ?: LoginFieldInlineModePerField;
    BOOL extra = [LoginAssistPreferences loginExtraFieldInlineEnabled];
    BOOL focusInline = [LoginAssistPreferences loginFocusInlineEnabled];
    NSString *source = [NSString stringWithFormat:
                        @"window.__meoLoginInlineEnabled=%@;\n"
                        @"window.__meoLoginFieldInlineMode='%@';\n"
                        @"window.__meoLoginExtraFieldInlineEnabled=%@;\n"
                        @"window.__meoLoginFocusInlineEnabled=%@;\n%@",
                        enabled ? @"true" : @"false",
                        mode,
                        extra ? @"true" : @"false",
                        focusInline ? @"true" : @"false",
                        [self userScriptSource]];
    // 同源 iframe（如部分 uni-id 嵌入）也需要注入；跨域仍由主框架外挂兜底。
    WKUserScript *script = [[WKUserScript alloc] initWithSource:source
                                                  injectionTime:WKUserScriptInjectionTimeAtDocumentEnd
                                               forMainFrameOnly:NO];
    [ucc addUserScript:script];
}

+ (NSString *)javaScriptSettingFieldAssistTargets:(NSArray<NSDictionary *> *)targets {
    NSArray *safe = targets ?: @[];
    NSError *error = nil;
    NSData *data = [NSJSONSerialization dataWithJSONObject:safe options:0 error:&error];
    if (!data || error) {
        return @"try{if(window.__meoLoginAssistSetFieldTargets)window.__meoLoginAssistSetFieldTargets([]);}catch(e){}";
    }
    NSString *json = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding] ?: @"[]";
    return [NSString stringWithFormat:
            @"try{if(window.__meoLoginAssistSetFieldTargets)window.__meoLoginAssistSetFieldTargets(%@);}catch(e){}",
            json];
}

+ (NSArray<NSDictionary *> *)fieldAssistTargetDictionariesForRecipe:(LoginRecipe *)recipe
                                                       credentials:(LoginCredentials *)credentials
                                                    detectedSlots:(NSArray *)detectedSlots
                                          extraFieldInlineEnabled:(BOOL)extraEnabled {
    NSMutableArray<NSDictionary *> *out = [NSMutableArray array];
    if (![detectedSlots isKindOfClass:[NSArray class]]) {
        return out;
    }

    NSString *credUser = credentials.username ?: @"";
    NSString *credPass = credentials.password ?: @"";
    NSString *credPhone = credentials.phone ?: @"";

    for (id item in detectedSlots) {
        if (![item isKindOfClass:[NSDictionary class]]) {
            continue;
        }
        NSDictionary *slotInfo = (NSDictionary *)item;
        NSString *slot = slotInfo[@"slot"];
        NSString *detectedSel = slotInfo[@"selector"];
        if (![slot isKindOfClass:[NSString class]] || slot.length == 0) {
            continue;
        }
        if (![detectedSel isKindOfClass:[NSString class]]) {
            detectedSel = @"";
        }
        if ([slot isEqualToString:@"extra"] && !extraEnabled) {
            continue;
        }

        NSString *selector = detectedSel;
        BOOL hasPreset = NO;
        BOOL allowSave = YES;
        NSString *label = slot;

        if ([slot isEqualToString:@"username"]) {
            label = @"用户名";
            if (recipe.usernameSelector.length > 0) {
                selector = recipe.usernameSelector;
            }
            hasPreset = (credUser.length > 0);
        } else if ([slot isEqualToString:@"password"]) {
            label = @"密码";
            if (recipe.passwordSelector.length > 0) {
                selector = recipe.passwordSelector;
            }
            hasPreset = (credPass.length > 0);
        } else if ([slot isEqualToString:@"phone"]) {
            label = @"手机号";
            if (recipe.phoneSelector.length > 0) {
                selector = recipe.phoneSelector;
            }
            hasPreset = (credPhone.length > 0);
        } else if ([slot isEqualToString:@"otp"]) {
            label = @"验证码";
            allowSave = NO;
            if (recipe.otpSelector.length > 0) {
                selector = recipe.otpSelector;
                hasPreset = YES;
            } else {
                continue; // 无 otp 预设则不显示图标
            }
        } else if ([slot isEqualToString:@"extra"]) {
            NSString *detLabel = slotInfo[@"label"];
            if ([detLabel isKindOfClass:[NSString class]] && detLabel.length > 0) {
                label = detLabel;
            } else {
                label = @"字段";
            }
            hasPreset = NO;
            if (recipe) {
                for (LoginRecipeExtraField *ef in recipe.extraFields) {
                    if (ef.selector.length > 0 && [ef.selector isEqualToString:detectedSel] && ef.value.length > 0) {
                        hasPreset = YES;
                        selector = ef.selector;
                        if (ef.label.length > 0) {
                            label = ef.label;
                        }
                        break;
                    }
                }
            }
        } else {
            continue;
        }

        if (selector.length == 0) {
            continue;
        }

        [out addObject:@{
            @"slot": slot,
            @"selector": selector,
            @"hasPreset": @(hasPreset),
            @"allowSave": @(allowSave),
            @"label": label ?: @"",
        }];
    }
    return out;
}

+ (NSString *)userScriptSource {
    NSString *suppressFn = [BrowserRiskHostPolicy javaScriptShouldSuppressPageAutomationFunctionNamed:@"meoShouldSuppressLoginAssist"];
    NSString *prefix = [NSString stringWithFormat:
        @"(function() {\n"
        "  if (window.__meoLoginFormInlineInstalled) { return; }\n"
        "  if (window.__meoLoginInlineEnabled === false) { return; }\n"
        "%@"
        "  if (meoShouldSuppressLoginAssist()) { return; }\n"
        "  window.__meoLoginFormInlineInstalled = true;\n",
        suppressFn];

    NSString *body = [self userScriptSourceBody];
    return [prefix stringByAppendingString:body];
}

+ (NSString *)userScriptSourceBody {
    return @
"  const HANDLER = 'loginFormInline';\n"
"  const BTN_ATTR = 'data-meo-login-assist';\n"
"  const FIELD_BTN = 'meo-login-field-btn';\n"
"  const MENU_BTN = 'meo-login-menu-btn';\n"
"  const CROSS_BTN = 'meo-login-cross-frame-btn';\n"
"  const FOCUS_KEY = 'focus:active';\n"
"  const EMPTY_STREAK = 8;\n"
"  const PULSE_MS = 8000;\n"
"  const FIELD_SIZE = 28;\n"
"  const MENU_SIZE = 22;\n"
"  const FIELD_GAP = 6;\n"
"  let debounceTimer = null;\n"
"  let layoutTimer = null;\n"
"  let focusHideTimer = null;\n"
"  let activeFormId = null;\n"
"  let emptyStreak = 0;\n"
"  let paused = false;\n"
"  let scrollBound = false;\n"
"  let layoutBound = false;\n"
"  let pulseTimer = null;\n"
"  let fieldTargets = [];\n"
"  let lastContexts = [];\n"
"  let focusSlot = null;\n"
"  let suppressMODepth = 0;\n"
"  let lastDetectSig = '';\n"
"  const drafts = {};\n"
"  function isPerField() { return (window.__meoLoginFieldInlineMode || 'perField') !== 'legacySingleKey'; }\n"
"  function extraEnabled() { return window.__meoLoginExtraFieldInlineEnabled === true; }\n"
"  function focusModeEnabled() { return window.__meoLoginFocusInlineEnabled !== false; }\n"
"  function framePrefix() {\n"
"    if (window === window.top) return '';\n"
"    try { return 'f:' + String(location.host || '') + String(location.pathname || '').slice(0, 48) + ':'; } catch (e) { return 'f:child:'; }\n"
"  }\n"
"\n"
"  function post(payload) {\n"
"    try {\n"
"      const p = Object.assign({ frameHref: (location.href || '') }, payload || {});\n"
"      window.webkit.messageHandlers[HANDLER].postMessage(p);\n"
"    } catch (e) {}\n"
"  }\n"
"  function looksLikeLoginPage() {\n"
"    try {\n"
"      const blob = ((location.href || '') + ' ' + (document.title || '') + ' ' + (location.hash || '')).toLowerCase();\n"
"      return /(login|signin|sign-in|auth|passport|oauth|sso|\\/account|uni-id|登录|登陸|註冊|注册|cardlogin)/i.test(blob);\n"
"    } catch (e) { return false; }\n"
"  }\n"
"  function hasPasswordCandidate() {\n"
"    try {\n"
"      return !!document.querySelector(\n"
"        'input[type=\"password\"],' +\n"
"        'input[autocomplete*=\"current-password\"],' +\n"
"        'input[autocomplete*=\"new-password\"]'\n"
"      );\n"
"    } catch (e) { return true; }\n"
"  }\n"
"  function hasLoginCandidate() {\n"
"    try {\n"
"      if (hasPasswordCandidate()) return true;\n"
"      if (document.querySelector(\n"
"        'input[type=\"tel\"],input[type=\"email\"],' +\n"
"        'input[autocomplete*=\"tel\"],input[autocomplete*=\"username\"],' +\n"
"        'input[autocomplete*=\"one-time-code\"]'\n"
"      )) return true;\n"
"      if (document.querySelector(\n"
"        'input[placeholder*=\"手机\"],input[placeholder*=\"帳號\"],input[placeholder*=\"账号\"],' +\n"
"        'input[placeholder*=\"帐号\"],input[placeholder*=\"邮箱\"],input[placeholder*=\"郵箱\"],' +\n"
"        'input[placeholder*=\"验证码\"],input[placeholder*=\"驗證碼\"],input[placeholder*=\"卡号\"],' +\n"
"        'input[placeholder*=\"设备\"],input[placeholder*=\"密碼\"],input[placeholder*=\"密码\"],' +\n"
"        'input[name*=\"phone\"],input[name*=\"mobile\"],input[id*=\"phone\"],input[id*=\"login\"]'\n"
"      )) return true;\n"
"      if (looksLikeLoginPage() && document.querySelector('input[type=\"text\"],input[type=\"number\"],input:not([type])')) return true;\n"
"      return false;\n"
"    } catch (e) { return true; }\n"
"  }\n"
"  function visible(el) {\n"
"    if (!el || el.disabled) return false;\n"
"    const st = window.getComputedStyle(el);\n"
"    if (st.display === 'none' || st.visibility === 'hidden' || st.opacity === '0') return false;\n"
"    const r = el.getBoundingClientRect();\n"
"    return r.width > 0 && r.height > 0;\n"
"  }\n"
"  function textBlob(el) {\n"
"    return [el.name, el.id, el.placeholder, el.getAttribute('aria-label'), el.autocomplete, el.getAttribute('data-placeholder')]\n"
"      .filter(Boolean).join(' ').toLowerCase();\n"
"  }\n"
"  function nearbyLabelText(el) {\n"
"    try {\n"
"      if (el.id) {\n"
"        const lab = document.querySelector('label[for=\"' + CSS.escape(el.id) + '\"]');\n"
"        if (lab && lab.textContent) return lab.textContent.trim();\n"
"      }\n"
"      const p = el.parentElement;\n"
"      if (p && p.textContent) return p.textContent.trim().slice(0, 80);\n"
"    } catch (e) {}\n"
"    return '';\n"
"  }\n"
"  function fieldLabel(el) {\n"
"    try {\n"
"      if (el.id) {\n"
"        const lab = document.querySelector('label[for=\"' + CSS.escape(el.id) + '\"]');\n"
"        if (lab && lab.textContent) return lab.textContent.trim().replace(/\\s+/g, ' ').slice(0, 40);\n"
"      }\n"
"    } catch (e) {}\n"
"    return (el.placeholder || el.name || el.id || '字段').toString().slice(0, 40);\n"
"  }\n"
"  function isIdentifierField(el) {\n"
"    if (!el || el.tagName !== 'INPUT' || !visible(el)) return false;\n"
"    const t = (el.type || 'text').toLowerCase();\n"
"    if (t === 'password' || t === 'hidden' || t === 'submit' || t === 'button' || t === 'checkbox' || t === 'radio' || t === 'search' || t === 'file') return false;\n"
"    if (t !== 'text' && t !== 'number' && t !== '') return false;\n"
"    const blob = textBlob(el) + ' ' + nearbyLabelText(el).toLowerCase();\n"
"    return /(卡号|卡號|设备号|設備號|设备\\/卡|iccid|imei|card\\s*(no|num|id)|device\\s*(id|no|num)|卡密)/i.test(blob);\n"
"  }\n"
"  function isAccountField(el) {\n"
"    if (!el || el.tagName !== 'INPUT' || !visible(el)) return false;\n"
"    const t = (el.type || 'text').toLowerCase();\n"
"    if (t === 'password' || t === 'hidden' || t === 'submit' || t === 'button' || t === 'checkbox' || t === 'radio' || t === 'search' || t === 'file') return false;\n"
"    if (t === 'email' || t === 'tel') return true;\n"
"    if (isIdentifierField(el)) return true;\n"
"    if (t !== 'text' && t !== 'number' && t !== '') return false;\n"
"    const ac = (el.autocomplete || '').toLowerCase();\n"
"    if (/(username|email|tel|nickname|name)/.test(ac)) return true;\n"
"    const blob = textBlob(el) + ' ' + nearbyLabelText(el).toLowerCase();\n"
"    return /(user|login|account|email|mail|手机|手機|帐号|账号|帳號|邮箱|郵箱|phone|mobile)/i.test(blob);\n"
"  }\n"
"  function isPhoneField(el) {\n"
"    if (!el || el.tagName !== 'INPUT' || !visible(el)) return false;\n"
"    const t = (el.type || 'text').toLowerCase();\n"
"    if (t === 'tel') return true;\n"
"    const ac = (el.autocomplete || '').toLowerCase();\n"
"    if (ac.indexOf('tel') >= 0) return true;\n"
"    const blob = textBlob(el) + ' ' + nearbyLabelText(el).toLowerCase();\n"
"    return /(手机|手機|phone|mobile|tel)/i.test(blob) && !/(user|login|account|email|mail|帐号|账号|帳號|邮箱|郵箱)/i.test(blob);\n"
"  }\n"
"  function isPasswordField(el) {\n"
"    if (!el || el.tagName !== 'INPUT' || !visible(el)) return false;\n"
"    const t = (el.type || '').toLowerCase();\n"
"    if (t === 'password') return true;\n"
"    const ac = (el.autocomplete || '').toLowerCase();\n"
"    return ac.indexOf('current-password') >= 0 || ac.indexOf('new-password') >= 0;\n"
"  }\n"
"  function isOTPField(el) {\n"
"    if (!el || el.tagName !== 'INPUT' || !visible(el)) return false;\n"
"    const ac = (el.autocomplete || '').toLowerCase();\n"
"    if (ac.indexOf('one-time-code') >= 0) return true;\n"
"    const blob = textBlob(el) + ' ' + nearbyLabelText(el).toLowerCase();\n"
"    return /(otp|验证码|驗證碼|校验码|校驗碼|auth.?code|(^|[^a-z])code([^a-z]|$))/i.test(blob) && !/(邮|郵|zip|postal)/i.test(blob);\n"
"  }\n"
"  function isEditableAssistInput(el) {\n"
"    if (!el || !visible(el)) return false;\n"
"    if (el.tagName === 'TEXTAREA') return true;\n"
"    if (el.tagName !== 'INPUT') return false;\n"
"    const t = (el.type || 'text').toLowerCase();\n"
"    if (t === 'hidden' || t === 'submit' || t === 'button' || t === 'checkbox' || t === 'radio' || t === 'file' || t === 'search' || t === 'range' || t === 'color' || t === 'image' || t === 'reset') return false;\n"
"    return true;\n"
"  }\n"
"  function isRegisterish(root) {\n"
"    const pw = Array.from(root.querySelectorAll('input')).filter(isPasswordField);\n"
"    if (pw.length < 2) return false;\n"
"    return pw.some(p => ((p.autocomplete || '').toLowerCase().indexOf('new-password') >= 0));\n"
"  }\n"
"  function cssPath(el) {\n"
"    if (!el || el.nodeType !== 1) return '';\n"
"    function esc(v) {\n"
"      if (window.CSS && CSS.escape) return CSS.escape(v);\n"
"      return String(v).replace(/[^a-zA-Z0-9_-]/g, '\\\\$&');\n"
"    }\n"
"    if (el.id) {\n"
"      const s = '#' + esc(el.id);\n"
"      try { if (document.querySelectorAll(s).length === 1) return s; } catch (e) {}\n"
"    }\n"
"    const name = el.getAttribute('name');\n"
"    if (name) {\n"
"      const s = el.tagName.toLowerCase() + '[name=\"' + name.replace(/\"/g, '\\\\\"') + '\"]';\n"
"      try { if (document.querySelectorAll(s).length === 1) return s; } catch (e) {}\n"
"    }\n"
"    const parts = [];\n"
"    let node = el;\n"
"    while (node && node.nodeType === 1 && node !== document.body && parts.length < 5) {\n"
"      let part = node.tagName.toLowerCase();\n"
"      const parent = node.parentElement;\n"
"      if (parent) {\n"
"        const siblings = Array.from(parent.children).filter(c => c.tagName === node.tagName);\n"
"        if (siblings.length > 1) part += ':nth-of-type(' + (siblings.indexOf(node) + 1) + ')';\n"
"      }\n"
"      parts.unshift(part);\n"
"      node = parent;\n"
"    }\n"
"    return parts.join(' > ');\n"
"  }\n"
"  function findSubmit(root, passEl) {\n"
"    let btn = root.querySelector('button[type=\"submit\"], input[type=\"submit\"]');\n"
"    if (btn && visible(btn)) return btn;\n"
"    const buttons = Array.from(root.querySelectorAll('button, input[type=\"button\"], [role=\"button\"]')).filter(visible);\n"
"    const hit = buttons.find(b => /(log\\s*in|sign\\s*in|登录|登陸|提交|signin|获取验证码|獲取驗證碼)/i.test((b.textContent || b.value || '') + ' ' + textBlob(b)));\n"
"    return hit || null;\n"
"  }\n"
"  function classifySlotForEl(el) {\n"
"    if (!el) return null;\n"
"    if (isPasswordField(el)) return 'password';\n"
"    if (isOTPField(el)) return 'otp';\n"
"    if (isPhoneField(el)) return 'phone';\n"
"    if (isIdentifierField(el)) return 'username';\n"
"    if (isAccountField(el)) {\n"
"      const phoneLike = isPhoneField(el) && !/(user|login|account|email|mail|帐号|账号|帳號|邮箱|郵箱)/i.test(textBlob(el));\n"
"      return phoneLike ? 'phone' : 'username';\n"
"    }\n"
"    if (isEditableAssistInput(el)) return 'extra';\n"
"    return null;\n"
"  }\n"
"  function buildSlots(ctx) {\n"
"    const slots = [];\n"
"    if (ctx.user) {\n"
"      const phoneLike = isPhoneField(ctx.user) && !/(user|login|account|email|mail|帐号|账号|帳號|邮箱|郵箱)/i.test(textBlob(ctx.user));\n"
"      const idLike = isIdentifierField(ctx.user);\n"
"      slots.push({ slot: phoneLike ? 'phone' : 'username', el: ctx.user, selector: cssPath(ctx.user), label: fieldLabel(ctx.user),\n"
"        hasValueInDOM: !!(ctx.user.value && String(ctx.user.value).trim()) });\n"
"      if (idLike) slots[slots.length - 1].label = fieldLabel(ctx.user) || '卡号/设备号';\n"
"    }\n"
"    if (ctx.phone && ctx.phone !== ctx.user) {\n"
"      slots.push({ slot: 'phone', el: ctx.phone, selector: cssPath(ctx.phone), label: fieldLabel(ctx.phone),\n"
"        hasValueInDOM: !!(ctx.phone.value && String(ctx.phone.value).trim()) });\n"
"    }\n"
"    if (ctx.pass) {\n"
"      slots.push({ slot: 'password', el: ctx.pass, selector: cssPath(ctx.pass), label: fieldLabel(ctx.pass),\n"
"        hasValueInDOM: !!(ctx.pass.value && String(ctx.pass.value).trim()) });\n"
"    }\n"
"    if (ctx.otpEl) {\n"
"      slots.push({ slot: 'otp', el: ctx.otpEl, selector: cssPath(ctx.otpEl), label: fieldLabel(ctx.otpEl),\n"
"        hasValueInDOM: !!(ctx.otpEl.value && String(ctx.otpEl.value).trim()) });\n"
"    }\n"
"    if (extraEnabled() && ctx.extras) {\n"
"      ctx.extras.forEach(function(ex) {\n"
"        slots.push({ slot: 'extra', el: ex, selector: cssPath(ex), label: fieldLabel(ex),\n"
"          hasValueInDOM: !!(ex.value && String(ex.value).trim()) });\n"
"      });\n"
"    }\n"
"    return slots;\n"
"  }\n"
"  function contextFromRoot(root, idx, idHint) {\n"
"    if (!root || isRegisterish(root)) return null;\n"
"    const inputs = Array.from(root.querySelectorAll('input'));\n"
"    const pass = inputs.find(isPasswordField) || null;\n"
"    const accounts = inputs.filter(function(el) { return isAccountField(el) || isIdentifierField(el); });\n"
"    let phone = inputs.find(function(el) { return isPhoneField(el); }) || null;\n"
"    let user = accounts.find(function(el) { return el !== phone; }) || accounts[0] || null;\n"
"    if (!user && phone) user = phone;\n"
"    if (phone === user) phone = inputs.find(function(el) { return isPhoneField(el) && el !== user; }) || null;\n"
"    const otpEl = inputs.find(isOTPField) || null;\n"
"    const submit = findSubmit(root, pass);\n"
"    const loginish = looksLikeLoginPage() || !!submit;\n"
"    const hasPair = !!(pass && (user || phone));\n"
"    const hasSms = !!((phone || user) && otpEl);\n"
"    const hasIdentity = !!((phone || user) && (loginish || otpEl));\n"
"    if (!hasPair && !hasSms && !hasIdentity) return null;\n"
"    if (!pass && !user && !phone) return null;\n"
"    const used = new Set([user, pass, phone, otpEl].filter(Boolean));\n"
"    const extras = inputs.filter(function(el) {\n"
"      if (used.has(el) || !visible(el) || isPasswordField(el) || isOTPField(el)) return false;\n"
"      const t = (el.type || 'text').toLowerCase();\n"
"      return t === 'text' || t === 'email' || t === 'tel' || t === 'number' || t === 'url' || t === '';\n"
"    });\n"
"    const anchor = pass || user || phone || otpEl;\n"
"    const formId = framePrefix() + (idHint || (root.id ? ('id:' + root.id) : ('auto:' + idx + ':' + cssPath(anchor))));\n"
"    return { root: root, user: user, pass: pass, phone: phone, otpEl: otpEl, extras: extras, submit: submit, otp: !!otpEl, formId: formId };\n"
"  }\n"
"  function contexts() {\n"
"    const results = [];\n"
"    const forms = Array.from(document.querySelectorAll('form'));\n"
"    const roots = forms.length ? forms : [document.body];\n"
"    roots.forEach(function(root, idx) {\n"
"      const ctx = contextFromRoot(root, idx, null);\n"
"      if (ctx) results.push(ctx);\n"
"    });\n"
"    if (!results.length && document.body) {\n"
"      const ctx = contextFromRoot(document.body, 0, 'body');\n"
"      if (ctx) {\n"
"        ctx.formId = framePrefix() + 'body:' + cssPath(ctx.pass || ctx.user || ctx.phone || ctx.otpEl);\n"
"        results.push(ctx);\n"
"      }\n"
"    }\n"
"    return results;\n"
"  }\n"
"  function ensureStyle() {\n"
"    if (document.getElementById('meo-login-assist-style')) return;\n"
"    const style = document.createElement('style');\n"
"    style.id = 'meo-login-assist-style';\n"
"    style.textContent = '' +\n"
"      'input[' + BTN_ATTR + '-host=\"1\"]{ padding-right: 40px !important; box-sizing: border-box !important; }' +\n"
"      'button.meo-login-assist-btn,button.' + FIELD_BTN + ',button.' + MENU_BTN + ',button.' + CROSS_BTN + '{' +\n"
"      'position:fixed;z-index:2147483647;border:0;cursor:pointer;' +\n"
"      'display:flex;align-items:center;justify-content:center;' +\n"
"      'box-shadow:0 0 0 1px rgba(0,0,0,0.08);' +\n"
"      'pointer-events:auto;touch-action:manipulation;-webkit-user-select:none;user-select:none;' +\n"
"      '}' +\n"
"      'button.' + FIELD_BTN + '{' +\n"
"      'width:' + FIELD_SIZE + 'px;height:' + FIELD_SIZE + 'px;padding:0;border-radius:6px;position:relative;' +\n"
"      '}' +\n"
"      'button.' + FIELD_BTN + '::before{' +\n"
"      'content:\"\";position:absolute;inset:-8px;border-radius:10px;' +\n"
"      '}' +\n"
"      'button.meo-login-assist-btn{background:rgba(128,128,128,0.18);font-size:12px;width:22px;height:22px;}' +\n"
"      'button.meo-login-assist-btn:hover{background:rgba(10,132,255,0.25);}' +\n"
"      'button.' + FIELD_BTN + '[data-meo-kind=\"plus\"]{background:rgba(128,128,128,0.22);color:inherit;font-size:16px;font-weight:600;}' +\n"
"      'button.' + FIELD_BTN + '[data-meo-kind=\"plus\"]:hover{background:rgba(10,132,255,0.32);}' +\n"
"      'button.' + FIELD_BTN + '[data-meo-kind=\"fill\"]{background:rgba(10,132,255,0.92);color:#fff;}' +\n"
"      'button.' + FIELD_BTN + '[data-meo-kind=\"fill\"]:hover{background:rgba(0,112,230,1);}' +\n"
"      'button.' + FIELD_BTN + '[data-meo-kind=\"fill\"]:active{background:rgba(0,96,200,1);transform:scale(0.96);}' +\n"
"      'button.' + MENU_BTN + '{background:rgba(128,128,128,0.18);font-size:11px;width:' + MENU_SIZE + 'px;height:' + MENU_SIZE + 'px;border-radius:5px;padding:0;}' +\n"
"      'button.' + MENU_BTN + ':hover{background:rgba(10,132,255,0.25);}' +\n"
"      'button.' + CROSS_BTN + '{background:rgba(10,132,255,0.92);color:#fff;font-size:12px;height:28px;padding:0 10px;border-radius:6px;white-space:nowrap;}';\n"
"    document.documentElement.appendChild(style);\n"
"  }\n"
"  function fillSvg() {\n"
"    return '<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13\" height=\"13\" viewBox=\"0 0 16 16\" fill=\"none\" aria-hidden=\"true\">' +\n"
"      '<path d=\"M3 2.5h7.5L13 5v8.5H3V2.5z\" stroke=\"#fff\" stroke-width=\"1.4\" fill=\"none\"/>' +\n"
"      '<path d=\"M10 2.5V5h2.5\" stroke=\"#fff\" stroke-width=\"1.4\" fill=\"none\"/>' +\n"
"      '<path d=\"M8 7v4.5M8 11.5L6.2 9.7M8 11.5l1.8-1.8\" stroke=\"#fff\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>' +\n"
"      '</svg>';\n"
"  }\n"
"  function queryBySelector(sel) {\n"
"    if (!sel) return null;\n"
"    try { return document.querySelector(sel); } catch (e) { return null; }\n"
"  }\n"
"  function targetForSlot(slot, selector) {\n"
"    for (let i = 0; i < fieldTargets.length; i++) {\n"
"      const t = fieldTargets[i];\n"
"      if (!t) continue;\n"
"      if (t.slot === slot && (!selector || !t.selector || t.selector === selector)) return t;\n"
"      if (selector && t.selector === selector) return t;\n"
"    }\n"
"    return null;\n"
"  }\n"
"  function rightSideAvoidPx(el) {\n"
"    const r = el.getBoundingClientRect();\n"
"    let avoid = 6;\n"
"    const roots = [];\n"
"    if (el.parentElement) roots.push(el.parentElement);\n"
"    if (el.parentElement && el.parentElement.parentElement) roots.push(el.parentElement.parentElement);\n"
"    roots.forEach(function(root) {\n"
"      Array.from(root.querySelectorAll('button, a, span, i, svg, img, [class*=\"icon\"], [class*=\"eye\"], [class*=\"code\"], [class*=\"scan\"], [class*=\"clear\"]')).forEach(function(k) {\n"
"        if (k === el) return;\n"
"        if (k.closest && (k.closest('button.' + FIELD_BTN) || k.closest('button.' + MENU_BTN) || k.closest('button.' + CROSS_BTN) || k.closest('button.meo-login-assist-btn'))) return;\n"
"        const kr = k.getBoundingClientRect();\n"
"        if (kr.width < 8 || kr.height < 8 || kr.width > 120) return;\n"
"        if (kr.left < r.right && kr.right > r.right - 56 && kr.top < r.bottom && kr.bottom > r.top) {\n"
"          avoid = Math.max(avoid, (r.right - kr.left) + 4);\n"
"        }\n"
"      });\n"
"    });\n"
"    return Math.min(avoid, Math.max(6, r.width / 2));\n"
"  }\n"
"  function clearLegacyButtons(keepIds) {\n"
"    suppressMODepth++;\n"
"    try {\n"
"    document.querySelectorAll('button.meo-login-assist-btn').forEach(btn => {\n"
"      const id = btn.getAttribute(BTN_ATTR);\n"
"      if (keepIds && keepIds.has(id)) return;\n"
"      btn.remove();\n"
"    });\n"
"    } finally { suppressMODepth = Math.max(0, suppressMODepth - 1); }\n"
"  }\n"
"  function clearFieldButtons() {\n"
"    suppressMODepth++;\n"
"    try {\n"
"    document.querySelectorAll('button.' + FIELD_BTN + ',button.' + MENU_BTN).forEach(b => b.remove());\n"
"    document.querySelectorAll('input[' + BTN_ATTR + '-host]').forEach(el => {\n"
"      el.removeAttribute(BTN_ATTR + '-host');\n"
"      el.removeAttribute('data-meo-pad');\n"
"      try { el.style.removeProperty('padding-right'); } catch (e) {}\n"
"    });\n"
"    focusSlot = null;\n"
"    } finally { suppressMODepth = Math.max(0, suppressMODepth - 1); }\n"
"  }\n"
"  function clearCrossFrameButtons(keepIds) {\n"
"    suppressMODepth++;\n"
"    try {\n"
"    document.querySelectorAll('button.' + CROSS_BTN).forEach(function(btn) {\n"
"      const id = btn.getAttribute('data-meo-cross-id');\n"
"      if (keepIds && keepIds.has(id)) return;\n"
"      btn.remove();\n"
"    });\n"
"    } finally { suppressMODepth = Math.max(0, suppressMODepth - 1); }\n"
"  }\n"
"  function removeOrphanFieldButtons(activeKeys) {\n"
"    document.querySelectorAll('button.' + FIELD_BTN).forEach(function(btn) {\n"
"      const k = btn.getAttribute('data-meo-key');\n"
"      if (!k || !activeKeys.has(k)) btn.remove();\n"
"    });\n"
"    document.querySelectorAll('button.' + MENU_BTN).forEach(function(btn) {\n"
"      const k = btn.getAttribute('data-meo-menu-key');\n"
"      if (!k || !activeKeys.has(k)) btn.remove();\n"
"    });\n"
"  }\n"
"  function fieldBtnKey(formCtx, slotInfo, idx) {\n"
"    return String(formCtx.formId) + ':' + slotInfo.slot + ':' + idx;\n"
"  }\n"
"  function updateButtonGeometry(btn, el) {\n"
"    const r = el.getBoundingClientRect();\n"
"    const visibleNow = r.width > 0 && r.height > 0 && r.bottom > 0 && r.top < window.innerHeight;\n"
"    if (!visibleNow) {\n"
"      if (btn.style.display !== 'none') btn.style.display = 'none';\n"
"      return;\n"
"    }\n"
"    const avoid = rightSideAvoidPx(el);\n"
"    const left = Math.round(Math.max(r.left + 6, r.right - FIELD_SIZE - avoid));\n"
"    const top = Math.round(r.top + (r.height - FIELD_SIZE) / 2);\n"
"    if (btn.style.position !== 'fixed') btn.style.position = 'fixed';\n"
"    if (btn.style.top !== top + 'px') btn.style.top = top + 'px';\n"
"    if (btn.style.left !== left + 'px') btn.style.left = left + 'px';\n"
"    if (btn.style.display !== 'flex') btn.style.display = 'flex';\n"
"    btn.style.pointerEvents = 'auto';\n"
"    const pad = Math.max(40, avoid + FIELD_SIZE + 4);\n"
"    const padKey = pad + 'px';\n"
"    if (el.getAttribute('data-meo-pad') !== padKey) {\n"
"      el.setAttribute('data-meo-pad', padKey);\n"
"      try { el.style.setProperty('padding-right', padKey, 'important'); } catch (e) {}\n"
"    }\n"
"  }\n"
"  function updateMenuGeometryOutside(menu, el) {\n"
"    const r = el.getBoundingClientRect();\n"
"    const visibleNow = r.width > 0 && r.height > 0 && r.bottom > 0 && r.top < window.innerHeight;\n"
"    if (!visibleNow) {\n"
"      menu.style.display = 'none';\n"
"      return;\n"
"    }\n"
"    menu.style.position = 'fixed';\n"
"    menu.style.top = Math.round(r.top + (r.height - MENU_SIZE) / 2) + 'px';\n"
"    menu.style.left = Math.round(r.right + FIELD_GAP) + 'px';\n"
"    menu.style.display = 'flex';\n"
"    menu.style.pointerEvents = 'auto';\n"
"  }\n"
"  function lastVisibleSlot(slots) {\n"
"    for (let i = slots.length - 1; i >= 0; i--) {\n"
"      if (slots[i].el && visible(slots[i].el)) return slots[i];\n"
"    }\n"
"    return null;\n"
"  }\n"
"  function bindMenuButtonEvents(menu, formCtx) {\n"
"    if (menu.getAttribute('data-meo-bound') === '1') return;\n"
"    menu.setAttribute('data-meo-bound', '1');\n"
"    menu.addEventListener('pointerdown', function(e) { e.preventDefault(); e.stopPropagation(); }, true);\n"
"    menu.addEventListener('pointerup', function(e) {\n"
"      e.preventDefault(); e.stopPropagation();\n"
"      const mr = menu.getBoundingClientRect();\n"
"      post({\n"
"        type: 'iconMenu', formId: formCtx.formId, hasOTP: !!formCtx.otp,\n"
"        usernameSelector: formCtx.user ? cssPath(formCtx.user) : '',\n"
"        passwordSelector: formCtx.pass ? cssPath(formCtx.pass) : '',\n"
"        phoneSelector: formCtx.phone ? cssPath(formCtx.phone) : '',\n"
"        submitSelector: formCtx.submit ? cssPath(formCtx.submit) : '',\n"
"        left: mr.left, top: mr.top, width: mr.width, height: mr.height,\n"
"        hasUsername: !!(formCtx.user && formCtx.user.value),\n"
"        hasPassword: !!(formCtx.pass && formCtx.pass.value)\n"
"      });\n"
"    }, true);\n"
"  }\n"
"  function placeContextMenuButton(formCtx, slots) {\n"
"    const anchor = lastVisibleSlot(slots);\n"
"    if (!anchor || !anchor.el) return null;\n"
"    ensureStyle();\n"
"    const menuKey = String(formCtx.formId) + ':menu';\n"
"    let menu = document.querySelector('button.' + MENU_BTN + '[data-meo-menu-key=\"' + menuKey.replace(/\\\\/g,'\\\\\\\\').replace(/\"/g,'\\\\\"') + '\"]');\n"
"    if (!menu) {\n"
"      menu = document.createElement('button');\n"
"      menu.type = 'button';\n"
"      menu.className = MENU_BTN;\n"
"      menu.setAttribute('data-meo-menu-key', menuKey);\n"
"      menu.setAttribute('aria-label', '登录助手菜单');\n"
"      menu.title = '登录助手菜单';\n"
"      menu.textContent = '\\u22EF';\n"
"      document.documentElement.appendChild(menu);\n"
"      bindMenuButtonEvents(menu, formCtx);\n"
"    }\n"
"    updateMenuGeometryOutside(menu, anchor.el);\n"
"    return menuKey;\n"
"  }\n"
"  function activateFieldButton(btn) {\n"
"    if (!btn || btn.getAttribute('data-meo-busy') === '1') return;\n"
"    btn.setAttribute('data-meo-busy', '1');\n"
"    setTimeout(function() { try { btn.removeAttribute('data-meo-busy'); } catch (e) {} }, 500);\n"
"    const kind = btn.getAttribute('data-meo-kind');\n"
"    const slot = btn.getAttribute('data-meo-slot') || '';\n"
"    const sel = btn.getAttribute('data-meo-selector') || '';\n"
"    const formId = btn.getAttribute('data-meo-form-id') || '';\n"
"    const label = btn.getAttribute('data-meo-label') || '';\n"
"    const el = queryBySelector(sel);\n"
"    if (kind === 'fill') {\n"
"      post({ type: 'fillField', slot: slot, selector: sel, formId: formId, href: location.href || '' });\n"
"      return;\n"
"    }\n"
"    const v = el ? (el.value || '').toString() : '';\n"
"    if (!v.trim()) {\n"
"      post({ type: 'saveFieldEmpty', slot: slot, formId: formId });\n"
"      return;\n"
"    }\n"
"    const ctx = lastContexts.find(function(c) { return c.formId === formId; }) || lastContexts[0];\n"
"    post({\n"
"      type: 'saveField', slot: slot, selector: sel, label: label, value: v,\n"
"      formId: formId, href: location.href || '',\n"
"      usernameSelector: ctx && ctx.user ? cssPath(ctx.user) : '',\n"
"      passwordSelector: ctx && ctx.pass ? cssPath(ctx.pass) : '',\n"
"      phoneSelector: ctx && ctx.phone ? cssPath(ctx.phone) : (slot === 'phone' ? sel : ''),\n"
"      submitSelector: ctx && ctx.submit ? cssPath(ctx.submit) : ''\n"
"    });\n"
"  }\n"
"  function bindFieldButtonEvents(btn) {\n"
"    if (btn.getAttribute('data-meo-bound') === '1') return;\n"
"    btn.setAttribute('data-meo-bound', '1');\n"
"    btn.addEventListener('pointerdown', function(e) {\n"
"      e.preventDefault();\n"
"      e.stopPropagation();\n"
"    }, true);\n"
"    btn.addEventListener('pointerup', function(e) {\n"
"      e.preventDefault();\n"
"      e.stopPropagation();\n"
"      activateFieldButton(btn);\n"
"    }, true);\n"
"    btn.addEventListener('click', function(e) {\n"
"      e.preventDefault();\n"
"      e.stopPropagation();\n"
"    }, true);\n"
"  }\n"
"  function placeLegacyButton(ctx) {\n"
"    const pass = ctx.pass || ctx.user || ctx.phone;\n"
"    if (!pass) return;\n"
"    ensureStyle();\n"
"    pass.setAttribute(BTN_ATTR + '-host', '1');\n"
"    let btn = document.querySelector('button.meo-login-assist-btn[' + BTN_ATTR + '=\"' + String(ctx.formId).replace(/\\\\/g,'\\\\\\\\').replace(/\"/g,'\\\\\"') + '\"]');\n"
"    if (!btn) {\n"
"      btn = document.createElement('button');\n"
"      btn.type = 'button';\n"
"      btn.className = 'meo-login-assist-btn';\n"
"      btn.setAttribute(BTN_ATTR, ctx.formId);\n"
"      btn.setAttribute('aria-label', '登录助手');\n"
"      btn.title = '登录助手';\n"
"      btn.textContent = '\\uD83D\\uDD11';\n"
"      btn.addEventListener('click', function(e) {\n"
"        e.preventDefault(); e.stopPropagation();\n"
"        const r = btn.getBoundingClientRect();\n"
"        post({\n"
"          type: 'iconClicked', formId: ctx.formId, hasOTP: !!ctx.otp,\n"
"          usernameSelector: ctx.user ? cssPath(ctx.user) : '',\n"
"          passwordSelector: ctx.pass ? cssPath(ctx.pass) : '',\n"
"          phoneSelector: ctx.phone ? cssPath(ctx.phone) : '',\n"
"          submitSelector: ctx.submit ? cssPath(ctx.submit) : '',\n"
"          left: r.left, top: r.top, width: r.width, height: r.height,\n"
"          hasUsername: !!(ctx.user && ctx.user.value), hasPassword: !!(ctx.pass && ctx.pass.value)\n"
"        });\n"
"      }, true);\n"
"      document.documentElement.appendChild(btn);\n"
"    }\n"
"    const r = pass.getBoundingClientRect();\n"
"    const avoid = rightSideAvoidPx(pass);\n"
"    btn.style.top = Math.round(r.top + (r.height - 22) / 2) + 'px';\n"
"    btn.style.left = Math.round(Math.max(r.left + 8, r.right - 26 - Math.max(0, avoid - 6))) + 'px';\n"
"    btn.style.display = visible(pass) ? 'flex' : 'none';\n"
"  }\n"
"  function placeFieldButton(el, slotInfo, idx, formCtx) {\n"
"    if (!el || !visible(el)) return null;\n"
"    ensureStyle();\n"
"    const tgt = targetForSlot(slotInfo.slot, slotInfo.selector);\n"
"    const hasPreset = !!(tgt && tgt.hasPreset);\n"
"    const allowSave = tgt ? (tgt.allowSave !== false) : (slotInfo.slot !== 'otp');\n"
"    if (slotInfo.slot === 'otp' && !hasPreset) return null;\n"
"    if (!hasPreset && !allowSave) return null;\n"
"    const kind = hasPreset ? 'fill' : 'plus';\n"
"    if (kind === 'plus' && !allowSave) return null;\n"
"    el.setAttribute(BTN_ATTR + '-host', '1');\n"
"    const key = fieldBtnKey(formCtx, slotInfo, idx);\n"
"    const sel = (tgt && tgt.selector) || slotInfo.selector;\n"
"    let btn = document.querySelector('button.' + FIELD_BTN + '[data-meo-key=\"' + key.replace(/\\\\/g,'\\\\\\\\').replace(/\"/g,'\\\\\"') + '\"]');\n"
"    if (!btn) {\n"
"      btn = document.createElement('button');\n"
"      btn.type = 'button';\n"
"      btn.className = FIELD_BTN;\n"
"      btn.setAttribute('data-meo-key', key);\n"
"      document.documentElement.appendChild(btn);\n"
"      bindFieldButtonEvents(btn);\n"
"    }\n"
"    const label = (tgt && tgt.label) || slotInfo.label || '';\n"
"    const prevKind = btn.getAttribute('data-meo-kind');\n"
"    btn.setAttribute('data-meo-slot', slotInfo.slot);\n"
"    btn.setAttribute('data-meo-selector', sel);\n"
"    btn.setAttribute('data-meo-form-id', formCtx.formId);\n"
"    btn.setAttribute('data-meo-label', label);\n"
"    if (prevKind !== kind) {\n"
"      btn.setAttribute('data-meo-kind', kind);\n"
"      if (kind === 'plus') {\n"
"        btn.textContent = '+';\n"
"      } else {\n"
"        btn.innerHTML = fillSvg();\n"
"      }\n"
"    }\n"
"    if (kind === 'plus') {\n"
"      btn.setAttribute('aria-label', '保存到登录助手');\n"
"      const t = '保存到登录助手' + (label ? ('：' + label) : '');\n"
"      if (btn.title !== t) btn.title = t;\n"
"    } else {\n"
"      btn.setAttribute('aria-label', '填入登录助手：' + (label || slotInfo.slot));\n"
"      const t = '填入登录配置' + (label ? ('：' + label) : '');\n"
"      if (btn.title !== t) btn.title = t;\n"
"    }\n"
"    updateButtonGeometry(btn, el);\n"
"    return key;\n"
"  }\n"
"  function syncFieldButtons(removeOrphans) {\n"
"    if (!isPerField()) return;\n"
"    suppressMODepth++;\n"
"    try {\n"
"    const activeKeys = new Set();\n"
"    lastContexts.forEach(function(ctx) {\n"
"      const slots = buildSlots(ctx);\n"
"      slots.forEach(function(s, idx) {\n"
"        const k = placeFieldButton(s.el, s, idx, ctx);\n"
"        if (k) activeKeys.add(k);\n"
"      });\n"
"      const menuKey = placeContextMenuButton(ctx, slots);\n"
"      if (menuKey) activeKeys.add(menuKey);\n"
"    });\n"
"    if (focusSlot && focusSlot.el && visible(focusSlot.el)) {\n"
"      let covered = false;\n"
"      lastContexts.forEach(function(ctx) {\n"
"        buildSlots(ctx).forEach(function(s) { if (s.el === focusSlot.el) covered = true; });\n"
"      });\n"
"      if (!covered) {\n"
"        const fakeCtx = { formId: framePrefix() + 'focus', user: null, pass: null, phone: null, otp: false, submit: null };\n"
"        if (focusSlot.slot === 'phone') fakeCtx.phone = focusSlot.el;\n"
"        else if (focusSlot.slot === 'password') fakeCtx.pass = focusSlot.el;\n"
"        else fakeCtx.user = focusSlot.el;\n"
"        const k = placeFieldButton(focusSlot.el, focusSlot, 0, fakeCtx);\n"
"        if (k) activeKeys.add(k);\n"
"      }\n"
"    }\n"
"    if (removeOrphans) removeOrphanFieldButtons(activeKeys);\n"
"    } finally { suppressMODepth = Math.max(0, suppressMODepth - 1); }\n"
"  }\n"
"  function isLoginIframe(iframe) {\n"
"    const src = iframe.src || iframe.getAttribute('src') || '';\n"
"    const id = iframe.id || '';\n"
"    const name = iframe.name || '';\n"
"    const cls = iframe.className || '';\n"
"    return id === 'loginFrame' || /(login|signin|passport|account\\.|uni-id|oauth|auth|sso|havana)/i.test(src + ' ' + id + ' ' + name + ' ' + cls);\n"
"  }\n"
"  function placeCrossFrameBadge(iframe, id) {\n"
"    ensureStyle();\n"
"    let btn = document.querySelector('button.' + CROSS_BTN + '[data-meo-cross-id=\"' + id.replace(/\\\\/g,'\\\\\\\\').replace(/\"/g,'\\\\\"') + '\"]');\n"
"    if (!btn) {\n"
"      btn = document.createElement('button');\n"
"      btn.type = 'button';\n"
"      btn.className = CROSS_BTN;\n"
"      btn.setAttribute('data-meo-cross-id', id);\n"
"      btn.textContent = '登录助手';\n"
"      btn.title = '登录表单位于跨域框架内，点击打开登录助手';\n"
"      btn.addEventListener('pointerdown', function(e) { e.preventDefault(); e.stopPropagation(); }, true);\n"
"      btn.addEventListener('pointerup', function(e) {\n"
"        e.preventDefault(); e.stopPropagation();\n"
"        const r = btn.getBoundingClientRect();\n"
"        post({\n"
"          type: 'crossFrameAssist', formId: id, iframeSrc: iframe.src || '',\n"
"          left: r.left, top: r.top, width: r.width, height: r.height,\n"
"          hasOTP: false, usernameSelector: '', passwordSelector: '', submitSelector: ''\n"
"        });\n"
"      }, true);\n"
"      document.documentElement.appendChild(btn);\n"
"    }\n"
"    const r = iframe.getBoundingClientRect();\n"
"    btn.style.top = Math.round(Math.max(8, r.top + 8)) + 'px';\n"
"    btn.style.left = Math.round(Math.max(8, r.right - 96)) + 'px';\n"
"    btn.style.display = (r.width > 40 && r.height > 40) ? 'flex' : 'none';\n"
"  }\n"
"  function syncCrossFrameBadges() {\n"
"    if (window !== window.top) {\n"
"      clearCrossFrameButtons(null);\n"
"      return;\n"
"    }\n"
"    suppressMODepth++;\n"
"    try {\n"
"    const keep = new Set();\n"
"    Array.from(document.querySelectorAll('iframe')).forEach(function(iframe, idx) {\n"
"      if (!visible(iframe) || !isLoginIframe(iframe)) return;\n"
"      let sameOrigin = false;\n"
"      try { sameOrigin = !!(iframe.contentDocument || iframe.contentWindow.document); } catch (e) { sameOrigin = false; }\n"
"      if (sameOrigin) return;\n"
"      const id = 'cross:' + (iframe.id || idx) + ':' + String(iframe.src || '').slice(0, 80);\n"
"      keep.add(id);\n"
"      placeCrossFrameBadge(iframe, id);\n"
"    });\n"
"    clearCrossFrameButtons(keep);\n"
"    } finally { suppressMODepth = Math.max(0, suppressMODepth - 1); }\n"
"  }\n"
"  function scheduleLayoutSync() {\n"
"    if (layoutTimer) clearTimeout(layoutTimer);\n"
"    layoutTimer = setTimeout(function() {\n"
"      syncFieldButtons(false);\n"
"      syncCrossFrameBadges();\n"
"    }, 16);\n"
"  }\n"
"  function bindLayoutSync(on) {\n"
"    if (on && !layoutBound) {\n"
"      window.addEventListener('scroll', scheduleLayoutSync, true);\n"
"      window.addEventListener('resize', scheduleLayoutSync);\n"
"      layoutBound = true;\n"
"    } else if (!on && layoutBound) {\n"
"      window.removeEventListener('scroll', scheduleLayoutSync, true);\n"
"      window.removeEventListener('resize', scheduleLayoutSync);\n"
"      layoutBound = false;\n"
"    }\n"
"  }\n"
"  function collectFilledFields(ctx) {\n"
"    return buildSlots(ctx).filter(function(s) {\n"
"      if (s.slot === 'otp') return false;\n"
"      return !!(s.el && s.el.value && String(s.el.value).trim());\n"
"    }).map(function(s) {\n"
"      return { slot: s.slot, selector: s.selector, label: s.label, value: String(s.el.value) };\n"
"    });\n"
"  }\n"
"  window.__meoLoginAssistCollectFormFields = function(formId) {\n"
"    const ctx = lastContexts.find(function(c) { return c.formId === formId; }) || lastContexts[0];\n"
"    if (!ctx) return [];\n"
"    return collectFilledFields(ctx);\n"
"  };\n"
"  window.__meoLoginAssistSetFieldTargets = function(targets, fromParent) {\n"
"    fieldTargets = Array.isArray(targets) ? targets : [];\n"
"    if (isPerField()) syncFieldButtons(true);\n"
"    if (!fromParent && window === window.top) {\n"
"      for (let i = 0; i < window.frames.length; i++) {\n"
"        try {\n"
"          const f = window.frames[i];\n"
"          if (f && typeof f.__meoLoginAssistSetFieldTargets === 'function') {\n"
"            f.__meoLoginAssistSetFieldTargets(targets, true);\n"
"          }\n"
"        } catch (e) {}\n"
"      }\n"
"    }\n"
"  };\n"
"  function bindDraft(ctx) {\n"
"    if (drafts[ctx.formId]) return;\n"
"    drafts[ctx.formId] = { dirty: false };\n"
"    const mark = function() {\n"
"      const hasU = !!(ctx.user && ctx.user.value);\n"
"      const hasP = !!(ctx.pass && ctx.pass.value);\n"
"      if (hasU && hasP) {\n"
"        drafts[ctx.formId].dirty = true;\n"
"        drafts[ctx.formId].username = ctx.user.value;\n"
"        drafts[ctx.formId].password = ctx.pass.value;\n"
"        drafts[ctx.formId].usernameSelector = cssPath(ctx.user);\n"
"        drafts[ctx.formId].passwordSelector = cssPath(ctx.pass);\n"
"        drafts[ctx.formId].submitSelector = ctx.submit ? cssPath(ctx.submit) : '';\n"
"        drafts[ctx.formId].submitByEnter = true;\n"
"        post({ type: 'credentialsDraft', formId: ctx.formId, hasUsername: true, hasPassword: true });\n"
"      }\n"
"    };\n"
"    if (ctx.user) ctx.user.addEventListener('input', mark);\n"
"    if (ctx.pass) ctx.pass.addEventListener('input', mark);\n"
"    const root = ctx.root;\n"
"    if (root && root.tagName === 'FORM') {\n"
"      root.addEventListener('submit', function() {\n"
"        mark();\n"
"        if (drafts[ctx.formId] && drafts[ctx.formId].dirty) {\n"
"          drafts[ctx.formId].submittedAt = Date.now();\n"
"          post({ type: 'formSubmitted', formId: ctx.formId });\n"
"        }\n"
"      });\n"
"    }\n"
"  }\n"
"  function bindScroll(on) {\n"
"    if (on && !scrollBound) {\n"
"      window.addEventListener('scroll', schedule, true);\n"
"      scrollBound = true;\n"
"    } else if (!on && scrollBound) {\n"
"      window.removeEventListener('scroll', schedule, true);\n"
"      scrollBound = false;\n"
"    }\n"
"  }\n"
"  function setPaused(p) {\n"
"    if (p === paused) return;\n"
"    paused = p;\n"
"    if (p) {\n"
"      mo.disconnect();\n"
"      bindScroll(false);\n"
"      if (pulseTimer) clearInterval(pulseTimer);\n"
"      pulseTimer = setInterval(function() {\n"
"        if (hasLoginCandidate()) rearm();\n"
"      }, PULSE_MS);\n"
"    } else {\n"
"      if (pulseTimer) { clearInterval(pulseTimer); pulseTimer = null; }\n"
"      mo.observe(document.documentElement, { childList: true, subtree: true });\n"
"      emptyStreak = 0;\n"
"    }\n"
"  }\n"
"  function rearm() {\n"
"    setPaused(false);\n"
"    schedule();\n"
"  }\n"
"  function updateFocusSlotFromEvent(t) {\n"
"    if (!focusModeEnabled() || !isPerField()) {\n"
"      focusSlot = null;\n"
"      return;\n"
"    }\n"
"    if (!t || !isEditableAssistInput(t)) {\n"
"      return;\n"
"    }\n"
"    if (t.classList && (t.classList.contains(FIELD_BTN) || t.classList.contains(MENU_BTN))) return;\n"
"    const slot = classifySlotForEl(t);\n"
"    if (!slot) return;\n"
"    // 非登录语义的普通框：仅在登录页或已有上下文时用 extra\n"
"    if (slot === 'extra' && !looksLikeLoginPage() && !lastContexts.length && !hasLoginCandidate()) return;\n"
"    focusSlot = { slot: slot, el: t, selector: cssPath(t), label: fieldLabel(t), hasValueInDOM: !!(t.value && String(t.value).trim()) };\n"
"    if (isPerField()) syncFieldButtons(true);\n"
"  }\n"
"  function scan() {\n"
"    syncCrossFrameBadges();\n"
"    if (!hasLoginCandidate()) {\n"
"      clearLegacyButtons();\n"
"      if (!focusSlot) clearFieldButtons();\n"
"      lastContexts = [];\n"
"      if (activeFormId) {\n"
"        activeFormId = null;\n"
"        lastDetectSig = '';\n"
"        post({ type: 'formCleared' });\n"
"      }\n"
"      bindScroll(false);\n"
"      if (!focusSlot) bindLayoutSync(false);\n"
"      emptyStreak++;\n"
"      if (!paused && emptyStreak >= EMPTY_STREAK) setPaused(true);\n"
"      return;\n"
"    }\n"
"    emptyStreak = 0;\n"
"    const list = contexts();\n"
"    lastContexts = list;\n"
"    const ids = new Set(list.map(c => c.formId));\n"
"    if (isPerField()) {\n"
"      clearLegacyButtons();\n"
"      syncFieldButtons(true);\n"
"      bindLayoutSync(true);\n"
"    } else {\n"
"      clearFieldButtons();\n"
"      clearLegacyButtons(ids);\n"
"      list.forEach(ctx => placeLegacyButton(ctx));\n"
"      bindLayoutSync(list.length > 0);\n"
"    }\n"
"    if (!list.length) {\n"
"      if (activeFormId) {\n"
"        activeFormId = null;\n"
"        lastDetectSig = '';\n"
"        post({ type: 'formCleared' });\n"
"      }\n"
"      bindScroll(false);\n"
"      return;\n"
"    }\n"
"    list.forEach(ctx => bindDraft(ctx));\n"
"    bindScroll(true);\n"
"    const primary = list[0];\n"
"    activeFormId = primary.formId;\n"
"    const slots = buildSlots(primary).map(function(s) {\n"
"      return { slot: s.slot, selector: s.selector, label: s.label, hasValueInDOM: s.hasValueInDOM };\n"
"    });\n"
"    const detectSig = [primary.formId, !!primary.otp, primary.user ? cssPath(primary.user) : '', primary.pass ? cssPath(primary.pass) : '', primary.phone ? cssPath(primary.phone) : '', primary.submit ? cssPath(primary.submit) : '', list.length, slots.map(function(s){ return s.slot + ':' + s.selector; }).join('|')].join('\\x1e');\n"
"    if (detectSig !== lastDetectSig) {\n"
"      lastDetectSig = detectSig;\n"
"      post({\n"
"        type: 'formDetected',\n"
"        formId: primary.formId,\n"
"        hasOTP: !!primary.otp,\n"
"        usernameSelector: primary.user ? cssPath(primary.user) : '',\n"
"        passwordSelector: primary.pass ? cssPath(primary.pass) : '',\n"
"        phoneSelector: primary.phone ? cssPath(primary.phone) : '',\n"
"        submitSelector: primary.submit ? cssPath(primary.submit) : '',\n"
"        formCount: list.length,\n"
"        slots: slots\n"
"      });\n"
"    }\n"
"  }\n"
"  function schedule() {\n"
"    if (meoShouldSuppressLoginAssist()) { try { mo.disconnect(); } catch (e) {} return; }\n"
"    if (debounceTimer) clearTimeout(debounceTimer);\n"
"    debounceTimer = setTimeout(scan, 250);\n"
"  }\n"
"  function setValueOnEl(el, value) {\n"
"    if (!el) return;\n"
"    el.focus();\n"
"    const proto = el.tagName === 'TEXTAREA' ? window.HTMLTextAreaElement.prototype : window.HTMLInputElement.prototype;\n"
"    const setter = Object.getOwnPropertyDescriptor(proto, 'value');\n"
"    if (setter && setter.set) setter.set.call(el, value || ''); else el.value = value || '';\n"
"    el.dispatchEvent(new Event('input', { bubbles: true }));\n"
"    el.dispatchEvent(new Event('change', { bubbles: true }));\n"
"  }\n"
"  window.__meoLoginAssistFill = function(userSel, passSel, username, password, submitSel, submit) {\n"
"    function qs(sel) { try { return document.querySelector(sel); } catch (e) { return null; } }\n"
"    setValueOnEl(qs(userSel), username || '');\n"
"    setValueOnEl(qs(passSel), password || '');\n"
"    if (submit && submitSel) {\n"
"      const btn = qs(submitSel);\n"
"      if (btn) btn.click();\n"
"    }\n"
"    if (window === window.top) {\n"
"      for (let i = 0; i < window.frames.length; i++) {\n"
"        try {\n"
"          const f = window.frames[i];\n"
"          if (f && f.__meoLoginAssistFill) f.__meoLoginAssistFill(userSel, passSel, username, password, submitSel, submit);\n"
"        } catch (e) {}\n"
"      }\n"
"    }\n"
"    return 'ok';\n"
"  };\n"
"  window.__meoLoginAssistFillSelector = function(sel, value, fromParent) {\n"
"    function qs(s) { try { return document.querySelector(s); } catch (e) { return null; } }\n"
"    const el = qs(sel);\n"
"    if (el) {\n"
"      setValueOnEl(el, value || '');\n"
"      return 'ok';\n"
"    }\n"
"    if (!fromParent && window === window.top) {\n"
"      for (let i = 0; i < window.frames.length; i++) {\n"
"        try {\n"
"          const f = window.frames[i];\n"
"          if (f && typeof f.__meoLoginAssistFillSelector === 'function') {\n"
"            const r = f.__meoLoginAssistFillSelector(sel, value, true);\n"
"            if (r === 'ok') return 'ok';\n"
"          }\n"
"        } catch (e) {}\n"
"      }\n"
"    }\n"
"    return 'missing';\n"
"  };\n"
"  window.__meoLoginAssistReadDraft = function(formId) {\n"
"    const d = drafts[formId];\n"
"    if (!d || !d.dirty) return null;\n"
"    return {\n"
"      username: d.username || '', password: d.password || '',\n"
"      usernameSelector: d.usernameSelector || '', passwordSelector: d.passwordSelector || '',\n"
"      submitSelector: d.submitSelector || '', submitByEnter: !!d.submitByEnter\n"
"    };\n"
"  };\n"
"  window.__meoLoginAssistConsumeDraftForSave = function() {\n"
"    for (const id in drafts) {\n"
"      if (drafts[id] && drafts[id].dirty) {\n"
"        const d = drafts[id];\n"
"        drafts[id].dirty = false;\n"
"        return {\n"
"          formId: id, username: d.username || '', password: d.password || '',\n"
"          usernameSelector: d.usernameSelector || '', passwordSelector: d.passwordSelector || '',\n"
"          submitSelector: d.submitSelector || '', submitByEnter: !!d.submitByEnter\n"
"        };\n"
"      }\n"
"    }\n"
"    return null;\n"
"  };\n"
"  function isMeoAssistNode(n) {\n"
"    if (!n || n.nodeType !== 1) return false;\n"
"    const el = n;\n"
"    if (el.id === 'meo-login-assist-style') return true;\n"
"    if (el.classList && (el.classList.contains(FIELD_BTN) || el.classList.contains(MENU_BTN) || el.classList.contains(CROSS_BTN) || el.classList.contains('meo-login-assist-btn'))) return true;\n"
"    return !!(el.closest && el.closest('button.' + FIELD_BTN + ',button.' + MENU_BTN + ',button.' + CROSS_BTN + ',button.meo-login-assist-btn'));\n"
"  }\n"
"  const mo = new MutationObserver(function(mutations) {\n"
"    if (suppressMODepth > 0) return;\n"
"    for (let i = 0; i < mutations.length; i++) {\n"
"      const m = mutations[i];\n"
"      const nodes = [];\n"
"      if (m.addedNodes) for (let j = 0; j < m.addedNodes.length; j++) nodes.push(m.addedNodes[j]);\n"
"      if (m.removedNodes) for (let j = 0; j < m.removedNodes.length; j++) nodes.push(m.removedNodes[j]);\n"
"      for (let j = 0; j < nodes.length; j++) {\n"
"        if (!isMeoAssistNode(nodes[j])) { schedule(); return; }\n"
"      }\n"
"    }\n"
"  });\n"
"  mo.observe(document.documentElement, { childList: true, subtree: true });\n"
"  window.addEventListener('resize', schedule);\n"
"  document.addEventListener('focusin', function(e) {\n"
"    const t = e.target;\n"
"    if (!t) return;\n"
"    if (t.tagName === 'INPUT' || t.tagName === 'TEXTAREA') {\n"
"      rearm();\n"
"      if (focusHideTimer) { clearTimeout(focusHideTimer); focusHideTimer = null; }\n"
"      updateFocusSlotFromEvent(t);\n"
"    }\n"
"  }, true);\n"
"  document.addEventListener('focusout', function(e) {\n"
"    if (!focusModeEnabled()) return;\n"
"    const related = e.relatedTarget;\n"
"    if (related && related.closest && (related.closest('button.' + FIELD_BTN) || related.closest('button.' + MENU_BTN))) return;\n"
"    if (focusHideTimer) clearTimeout(focusHideTimer);\n"
"    focusHideTimer = setTimeout(function() {\n"
"      focusSlot = null;\n"
"      if (isPerField()) syncFieldButtons(true);\n"
"    }, 280);\n"
"  }, true);\n"
"  schedule();\n"
"})();";
}

@end
