#import "BrowserScraperDetector.h"

@implementation BrowserScraperDetector

+ (NSString *)jsonStringLiteral:(NSString *)string {
    NSString *safe = [string isKindOfClass:[NSString class]] ? string : @"";
    NSError *error = nil;
    NSData *data = [NSJSONSerialization dataWithJSONObject:safe
                                                   options:NSJSONWritingFragmentsAllowed
                                                     error:&error];
    if (!data) {
        return @"\"\"";
    }
    return [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding] ?: @"\"\"";
}

/// 页面结构分析公共 JS（表格行 / ul·li / 同构卡片）。
+ (NSString *)structureHelpersJavaScript {
    return @
    "function meoEsc(v){ if(window.CSS&&CSS.escape) return CSS.escape(v); return String(v).replace(/[^a-zA-Z0-9_-]/g,'\\\\$&'); }\n"
    "function meoCssPath(el){\n"
    "  if(!el||el.nodeType!==1) return '';\n"
    "  if(el.id){ var s='#'+meoEsc(el.id); try{ if(document.querySelectorAll(s).length===1) return s; }catch(e){} }\n"
    "  var parts=[], node=el;\n"
    "  while(node&&node.nodeType===1&&node!==document.documentElement&&parts.length<7){\n"
    "    var part=node.tagName.toLowerCase();\n"
    "    var cls=Array.from(node.classList||[]).filter(function(c){return c&&!/^(active|hover|selected|open|show|is-|js-)/i.test(c);}).slice(0,2);\n"
    "    if(cls.length) part+='.'+cls.map(meoEsc).join('.');\n"
    "    var p=node.parentElement;\n"
    "    if(p){\n"
    "      var sib=Array.from(p.children).filter(function(c){return c.tagName===node.tagName;});\n"
    "      if(sib.length>1) part+=':nth-of-type('+(sib.indexOf(node)+1)+')';\n"
    "    }\n"
    "    parts.unshift(part); node=p;\n"
    "  }\n"
    "  return parts.join(' > ');\n"
    "}\n"
    "function meoFp(el){\n"
    "  if(!el||el.nodeType!==1) return '';\n"
    "  var tag=el.tagName.toLowerCase();\n"
    "  if(['script','style','svg','path','noscript','br','hr','meta','link'].indexOf(tag)>=0) return '';\n"
    "  var allCls=Array.from(el.classList||[]).filter(function(c){return c&&!/^(active|hover|selected|open|show|is-|js-|swiper|slick|el-|v-)/i.test(c);});\n"
    "  // 列表卡：优先用稳定业务 class 分组（如 company-card-wrapper），避免子节点细微差异拆散\n"
    "  var durable=allCls.find(function(c){\n"
    "    return /(card|item|result|company|product|goods|article|news|entity|record)[-_]?(wrapper|item|card|row|box|list)?$/i.test(c)\n"
    "      || /[-_](card|item|row)([-_]|$)/i.test(c)\n"
    "      || /^(card|item|row)([-_]|$)/i.test(c);\n"
    "  });\n"
    "  if(durable && durable.length>=4) return tag+'|.'+durable;\n"
    "  var cls=allCls.slice(0,4).sort().join('.');\n"
    "  var kids=Array.from(el.children||[]).slice(0,6).map(function(c){\n"
    "    var t=c.tagName.toLowerCase();\n"
    "    var k=Array.from(c.classList||[]).filter(function(x){return x&&!/^(active|hover|is-|el-|v-)/i.test(x);}).slice(0,1).join('');\n"
    "    return t+(k?('.'+k):'');\n"
    "  }).join(',');\n"
    "  return tag+'|'+cls+'|'+kids;\n"
    "}\n"
    "function meoRelPath(root, el){\n"
    "  if(!root||!el||!root.contains(el)) return '';\n"
    "  if(root===el) return '';\n"
    "  var tag=el.tagName.toLowerCase();\n"
    "  var allCls=Array.from(el.classList||[]);\n"
    "  for(var ci=0;ci<allCls.length;ci++){\n"
    "    // 淘宝等：name--hash\n"
    "    var cm=allCls[ci].match(/^([A-Za-z_][\\w]*)--[\\w-]+$/);\n"
    "    if(cm){\n"
    "      var modSel='[class*=\"'+cm[1]+'--\"]';\n"
    "      try{ if(root.querySelectorAll(modSel).length===1) return modSel; }catch(e){}\n"
    "    }\n"
    "    // 京东等：_price_9y3st_31\n"
    "    var um=allCls[ci].match(/^_([A-Za-z][\\w]*)_/);\n"
    "    if(um){\n"
    "      var uSel='[class*=\"_'+um[1]+'_\"]';\n"
    "      try{ if(root.querySelectorAll(uSel).length===1) return uSel; }catch(e){}\n"
    "    }\n"
    "  }\n"
    "  var cls=allCls.filter(function(c){return c&&!/^(active|hover|selected)/i.test(c);}).slice(0,2);\n"
    "  if(cls.length){\n"
    "    var sel=tag+'.'+cls.map(meoEsc).join('.');\n"
    "    try{ if(root.querySelectorAll(sel).length===1) return sel; }catch(e){}\n"
    "  }\n"
    "  if(tag==='a' && root.querySelectorAll('a').length===1) return 'a';\n"
    "  if(tag==='img' && root.querySelectorAll('img').length===1) return 'img';\n"
    "  var parts=[], node=el;\n"
    "  while(node&&node!==root&&parts.length<5){\n"
    "    var part=node.tagName.toLowerCase();\n"
    "    var p=node.parentElement;\n"
    "    if(p){\n"
    "      var sib=Array.from(p.children).filter(function(c){return c.tagName===node.tagName;});\n"
    "      if(sib.length>1) part+=':nth-of-type('+(sib.indexOf(node)+1)+')';\n"
    "    }\n"
    "    parts.unshift(part); node=node.parentElement;\n"
    "  }\n"
    "  return parts.join(' > ');\n"
    "}\n"
    "function meoItemScore(el){\n"
    "  if(!el) return 0;\n"
    "  var t=String(el.textContent||'').replace(/\\s+/g,' ').trim();\n"
    "  var score=0;\n"
    "  if(t.length>8) score+=2;\n"
    "  if(t.length>40) score+=2;\n"
    "  if(el.querySelector && el.querySelector('a[href]')) score+=3;\n"
    "  if(el.querySelector && el.querySelector('img[src]')) score+=1;\n"
    "  if(el.querySelector && el.querySelector('h1,h2,h3,h4,h5,h6')) score+=2;\n"
    "  if(el.children && el.children.length>=2) score+=1;\n"
    "  return score;\n"
    "}\n"
    "function meoInferFields(item){\n"
    "  var fields=[];\n"
    "  if(!item) return fields;\n"
    "  function push(name, kind, path, attr){\n"
    "    if(path==null) return;\n"
    "    var f={name:name, kind:kind||'text', path:path||''};\n"
    "    if(attr) f.attribute=attr;\n"
    "    for(var i=0;i<fields.length;i++){ if(fields[i].path===f.path&&fields[i].kind===f.kind&&fields[i].name===f.name) return; }\n"
    "    fields.push(f);\n"
    "  }\n"
    "  var selfLink=null;\n"
    "  try{ if(item.matches && item.matches('a[href]')) selfLink=item; }catch(e){}\n"
    "  if(!selfLink && item.tagName && item.tagName.toLowerCase()==='a' && item.getAttribute('href')) selfLink=item;\n"
    "\n"
    "  // —— 淘宝 / 京东等电商商品卡 ——\n"
    "  var priceBox=item.querySelector('[class*=\"innerPriceWrapper--\"]');\n"
    "  var priceInt=item.querySelector('[class*=\"priceInt--\"]');\n"
    "  if(!priceBox && priceInt) priceBox=priceInt.parentElement || priceInt;\n"
    "  var jdPrice=item.querySelector('[class*=\"_price_\"]');\n"
    "  var salesEl=item.querySelector('[class*=\"realSales--\"]');\n"
    "  var jdVolume=item.querySelector('[class*=\"_goods_volume_\"]');\n"
    "  var shopEl=item.querySelector('[class*=\"shopNameText--\"], [class*=\"shopName--\"]');\n"
    "  // 京东店名：优先 _limit_（纯店名），再退到 _name_\n"
    "  var jdShop=item.querySelector('[class*=\"_limit_\"]')\n"
    "    || item.querySelector('[class*=\"_name_\"] [class*=\"_limit_\"]')\n"
    "    || item.querySelector('[class*=\"_name_\"]');\n"
    "  var tbTitle=item.querySelector('[class*=\"descWrapper--\"] [class*=\"title--\"], [class*=\"title--\"][title], [class*=\"title--\"]');\n"
    "  var jdTitle=item.querySelector('[class*=\"_goods_title\"] [title], [class*=\"_goods_title_container\"] [title], [class*=\"_goods_title\"] span[title], [class*=\"_newStyle_\"][title]');\n"
    "  if(!jdTitle){\n"
    "    var titled=item.querySelector('[class*=\"_goods_title\"] span[title], [class*=\"_info_\"] span[title]');\n"
    "    if(titled) jdTitle=titled;\n"
    "  }\n"
    "  var tbImg=item.querySelector('img[class*=\"mainImg--\"], img[class*=\"mainPic--\"]');\n"
    "  var prodLink=selfLink || item.querySelector('a[href*=\"item.htm\"], a[href*=\"item.taobao\"], a[href*=\"detail.tmall\"], a[class*=\"doubleCardWrapper\"], a[href*=\"item.jd.com\"], a[href*=\"jd.com/product\"], a[href*=\"//item.jd\"], a[href*=\"npcitem.jd.com\"]');\n"
    "  var isTB=!!(priceInt || priceBox || salesEl || (shopEl && tbTitle));\n"
    "  var isJD=!!(jdPrice || (jdShop && jdTitle) || (jdTitle && item.querySelector('[class*=\"_info_\"],[class*=\"_goods_title\"]')));\n"
    "  if(isTB || isJD){\n"
    "    var titleEl=tbTitle || jdTitle;\n"
    "    if(titleEl){\n"
    "      if(titleEl.getAttribute && titleEl.getAttribute('title')) push('标题','attribute', meoRelPath(item,titleEl) || (isJD?'[class*=\"_goods_title\"] [title]':''), 'title');\n"
    "      else push('标题','text', meoRelPath(item,titleEl));\n"
    "    }\n"
    "    if(prodLink){\n"
    "      var prodLinkPath=(prodLink===item)?'':meoRelPath(item,prodLink);\n"
    "      push('链接','href', prodLinkPath, 'href');\n"
    "    }\n"
    "    if(tbImg) push('图片','src', meoRelPath(item,tbImg), 'src');\n"
    "    else {\n"
    "      var anyImg=item.querySelector('img[src]:not([class*=\"_link_icon\"]):not([class*=\"Tag\"])');\n"
    "      if(!anyImg) anyImg=item.querySelector('img[src]');\n"
    "      if(anyImg) push('图片','src', meoRelPath(item,anyImg), 'src');\n"
    "    }\n"
    "    if(priceBox) push('价格','text', meoRelPath(item,priceBox) || '[class*=\"innerPriceWrapper--\"]');\n"
    "    else if(priceInt){\n"
    "      var wrap=priceInt.parentElement;\n"
    "      if(wrap && item.contains(wrap)) push('价格','text', meoRelPath(item,wrap) || '[class*=\"innerPriceWrapper--\"]');\n"
    "      else push('价格','text', meoRelPath(item,priceInt) || '[class*=\"priceInt--\"]');\n"
    "    } else if(jdPrice){\n"
    "      push('价格','text', meoRelPath(item,jdPrice) || '[class*=\"_price_\"]');\n"
    "    }\n"
    "    if(salesEl) push('付款人数','text', meoRelPath(item,salesEl));\n"
    "    else if(jdVolume) push('销量','text', meoRelPath(item,jdVolume) || '[class*=\"_goods_volume_\"]');\n"
    "    if(shopEl){\n"
    "      var shopText=shopEl.querySelector ? (shopEl.querySelector('[class*=\"shopNameText--\"]')||shopEl) : shopEl;\n"
    "      push('店名','text', meoRelPath(item,shopText));\n"
    "    } else if(jdShop){\n"
    "      // 最兼容：_limit_ 纯文本店名；若点到 _name_ 再找内部 _limit_\n"
    "      var jdShopText=jdShop;\n"
    "      if(jdShop.querySelector){\n"
    "        var lim=jdShop.querySelector('[class*=\"_limit_\"]');\n"
    "        if(lim) jdShopText=lim;\n"
    "      }\n"
    "      push('店名','text', meoRelPath(item,jdShopText) || '[class*=\"_limit_\"]');\n"
    "    }\n"
    "    return fields.slice(0,10);\n"
    "  }\n"
    "\n"
    "  // —— 企查查 / 企知道等企业信息卡 ——\n"
    "  var companyName=item.querySelector('.companyName, [class*=\"companyName\"], .company-name, [class*=\"ent-name\"]');\n"
    "  var creditCode=item.querySelector('.credit-code .content-text, .credit-code, [class*=\"credit-code\"], [class*=\"creditCode\"]');\n"
    "  var isCompanyCard=!!(companyName || (item.classList && (item.classList.contains('company-card-wrapper') || Array.from(item.classList||[]).some(function(c){return /company[-_]?card/i.test(c);}))) || item.querySelector('.company-card-wrapper, .info-body, .registered-capital'));\n"
    "  if(isCompanyCard && (companyName || creditCode || item.querySelector('.status,[class*=\"registered-capital\"]'))){\n"
    "    var nameEl=companyName || item.querySelector('h1,h2,h3,h4 a, h2, h3');\n"
    "    var nameLink=(nameEl && nameEl.closest) ? (nameEl.closest('a[href]')||null) : null;\n"
    "    if(!nameLink) nameLink=item.querySelector('a[href*=\"/company/\"], a[href*=\"/ent/\"], .companyNameInfo a[href], .img-box a[href]');\n"
    "    if(nameEl) push('企业名称','text', meoRelPath(item,nameEl) || '.companyName');\n"
    "    if(nameLink){\n"
    "      var nameLinkPath=(nameLink===item)?'':(meoRelPath(item,nameLink) || 'a[href*=\"/company/\"]');\n"
    "      push('企业链接','href', nameLinkPath, 'href');\n"
    "    }\n"
    "    var statusEl=item.querySelector('.status, [class*=\"status\"]');\n"
    "    if(statusEl) push('经营状态','text', meoRelPath(item,statusEl) || '.status');\n"
    "    var legal=item.querySelector('.oper_name_overflow .content-text, .oper_name_overflow .text-overflow, [class*=\"oper_name\"]');\n"
    "    if(legal) push('法定代表人','text', meoRelPath(item,legal));\n"
    "    var capital=item.querySelector('.registered-capital .content-text, [class*=\"registered-capital\"] .content-text, [class*=\"registered-capital\"]');\n"
    "    if(capital) push('注册资本','text', meoRelPath(item,capital));\n"
    "    var founded=null;\n"
    "    Array.from(item.querySelectorAll('.content-box > span, .info-body span')).some(function(sp){\n"
    "      var tx=String(sp.textContent||'');\n"
    "      if(/成立日期/.test(tx)){\n"
    "        founded=sp.querySelector('.content-text')||sp;\n"
    "        return true;\n"
    "      }\n"
    "      return false;\n"
    "    });\n"
    "    if(founded) push('成立日期','text', meoRelPath(item,founded));\n"
    "    if(creditCode) push('统一社会信用代码','text', meoRelPath(item,creditCode) || '.credit-code .content-text');\n"
    "    var phone=item.querySelector('.phone .copy_text, .phone .copy-phone-box, .contact-info-website .phone');\n"
    "    if(phone) push('电话','text', meoRelPath(item,phone));\n"
    "    var email=item.querySelector('.email .copy_text, .email .text');\n"
    "    if(email) push('邮箱','text', meoRelPath(item,email));\n"
    "    var site=item.querySelector('.website .text, .website .item-box .text');\n"
    "    if(site) push('官网','text', meoRelPath(item,site));\n"
    "    var addr=item.querySelector('.address .copy-text, .address .text');\n"
    "    if(addr) push('地址','text', meoRelPath(item,addr));\n"
    "    var logo=item.querySelector('.img-box img, img.logo, img[alt]');\n"
    "    if(logo) push('Logo','src', meoRelPath(item,logo), 'src');\n"
    "    if(fields.length) return fields.slice(0,14);\n"
    "  }\n"
    "\n"
    "  var title=item.querySelector('h1,h2,h3,h4,h5,h6,[class*=\"title\"],[class*=\"Title\"],[class*=\"NAME\"]');\n"
    "  var link=selfLink || item.querySelector('a[href]');\n"
    "  var img=item.querySelector('img[src]');\n"
    "  var time=item.querySelector('time,[datetime],[class*=\"time\"],[class*=\"date\"],[class*=\"Date\"],[class*=\"Time\"],[class*=\"gray-400\"]');\n"
    "  var desc=null;\n"
    "  var descNodes=item.querySelectorAll('p,[class*=\"desc\"],[class*=\"summary\"],[class*=\"excerpt\"],[class*=\"intro\"],[class*=\"line-clamp\"]');\n"
    "  for(var di=0;di<descNodes.length;di++){\n"
    "    var d=descNodes[di];\n"
    "    if(/^H[1-6]$/.test(d.tagName)) continue;\n"
    "    if(title && (d===title || (title.contains&&title.contains(d)) || (d.contains&&d.contains(title)))) continue;\n"
    "    desc=d; break;\n"
    "  }\n"
    "  if(title) push('标题','text', meoRelPath(item,title));\n"
    "  else if(link && link!==item) push('标题','text', meoRelPath(item,link));\n"
    "  else push('文本','text','');\n"
    "  if(link){\n"
    "    var linkPath=(link===item) ? '' : meoRelPath(item,link);\n"
    "    push('链接','href', linkPath, 'href');\n"
    "  }\n"
    "  if(img) push('图片','src', meoRelPath(item,img), 'src');\n"
    "  if(time) push('时间','text', meoRelPath(item,time));\n"
    "  if(desc) push('摘要','text', meoRelPath(item,desc));\n"
    "  if(item.tagName && item.tagName.toLowerCase()==='tr'){\n"
    "    fields=[];\n"
    "    var cells=item.querySelectorAll(':scope > td, :scope > th');\n"
    "    if(!cells.length) cells=item.querySelectorAll('td,th');\n"
    "    Array.from(cells).slice(0,24).forEach(function(td,i){\n"
    "      var a=td.querySelector('a[href]');\n"
    "      var colName='列'+(i+1);\n"
    "      var tdSel='td:nth-child('+(i+1)+')';\n"
    "      // 超链接列：同时输出纯文本 + 链接\n"
    "      if(a){\n"
    "        push(colName,'text', tdSel);\n"
    "        push(colName+'链接','href', tdSel+' a','href');\n"
    "      } else {\n"
    "        push(colName,'text', tdSel);\n"
    "      }\n"
    "    });\n"
    "    return fields.slice(0,32);\n"
    "  }\n"
    "  return fields.slice(0,12);\n"
    "}\n"
    "function meoTableHeaderLabels(table){\n"
    "  function cleanHeads(nodes){\n"
    "    // 保留空表头占位，避免列索引与 tbody td 错位\n"
    "    return Array.from(nodes||[]).filter(function(th){\n"
    "      if(!th||!th.classList) return true;\n"
    "      if(th.classList.contains('gutter')) return false;\n"
    "      if(th.classList.contains('el-table-column--selection')) return false;\n"
    "      return true;\n"
    "    }).map(function(th){\n"
    "      var t=(th.textContent||'').replace(/\\s+/g,' ').trim();\n"
    "      if(t==='#') t='';\n"
    "      return t;\n"
    "    });\n"
    "  }\n"
    "  var heads=cleanHeads(table.querySelectorAll('thead th'));\n"
    "  if(heads.length) return heads;\n"
    "  // Element UI：表头常在兄弟 .el-table__header 表中\n"
    "  var root=table.closest ? (table.closest('.el-table')||table.closest('.el-table__body-wrapper')||table.parentElement) : table.parentElement;\n"
    "  if(root){\n"
    "    var scope=root.classList&&root.classList.contains('el-table')?root:(root.closest?root.closest('.el-table'):null)||root.parentElement||root;\n"
    "    heads=cleanHeads(scope.querySelectorAll('.el-table__header th, .el-table__header-wrapper th, thead th'));\n"
    "    if(heads.length) return heads;\n"
    "  }\n"
    "  return [];\n"
    "}\n"
    "function meoBuildTableFields(sample, heads){\n"
    "  var fields=[];\n"
    "  function add(name, kind, path, attr){\n"
    "    var f={name:name, kind:kind||'text', path:path||''};\n"
    "    if(attr) f.attribute=attr;\n"
    "    fields.push(f);\n"
    "  }\n"
    "  var cellCount=0;\n"
    "  if(sample){\n"
    "    var cells=sample.querySelectorAll(':scope > td, :scope > th');\n"
    "    if(!cells.length) cells=sample.querySelectorAll('td,th');\n"
    "    cellCount=cells.length;\n"
    "  }\n"
    "  var n=Math.max(heads.length||0, cellCount||0, 1);\n"
    "  n=Math.min(n, 24);\n"
    "  for(var i=0;i<n;i++){\n"
    "    var name=(heads[i]&&String(heads[i]).trim()) || ('列'+(i+1));\n"
    "    // 避免重名覆盖\n"
    "    var base=name, k=2;\n"
    "    while(fields.some(function(f){return f.name===name;})){ name=base+'_'+k; k++; }\n"
    "    var tdSel='td:nth-child('+(i+1)+')';\n"
    "    var hasLink=false;\n"
    "    try{ hasLink=!!(sample && sample.querySelector(tdSel+' a[href]')); }catch(e){}\n"
    "    if(hasLink){\n"
    "      add(name,'text', tdSel);\n"
    "      var linkName=name+'链接';\n"
    "      var lk=2;\n"
    "      while(fields.some(function(f){return f.name===linkName;})){ linkName=name+'链接_'+lk; lk++; }\n"
    "      add(linkName,'href', tdSel+' a','href');\n"
    "    } else {\n"
    "      add(name,'text', tdSel);\n"
    "    }\n"
    "  }\n"
    "  return fields;\n"
    "}\n"
    "function meoRowSelector(container, sample){\n"
    "  if(!container||!sample) return '';\n"
    "  var tag=sample.tagName.toLowerCase();\n"
    "  var cls=Array.from(sample.classList||[]).filter(function(c){return c&&!/^(active|hover|selected)/i.test(c);}).slice(0,3);\n"
    "  if(cls.length){\n"
    "    var sel=tag+'.'+cls.map(meoEsc).join('.');\n"
    "    try{ var n=container.querySelectorAll(sel).length; if(n>=3) return sel; }catch(e){}\n"
    "  }\n"
    "  if(sample.parentElement===container){\n"
    "    try{ if(container.querySelectorAll(':scope > '+tag).length>=3) return ':scope > '+tag; }catch(e){}\n"
    "    return tag;\n"
    "  }\n"
    "  var parent=sample.parentElement;\n"
    "  if(parent && container.contains(parent)){\n"
    "    var pCls=Array.from(parent.classList||[]).slice(0,2);\n"
    "    var pSel=parent.tagName.toLowerCase()+(pCls.length?('.'+pCls.map(meoEsc).join('.')):'');\n"
    "    var childSel=tag+(cls.length?('.'+cls.map(meoEsc).join('.')):'');\n"
    "    var full=pSel+' > '+childSel;\n"
    "    try{ if(container.querySelectorAll(full).length>=3) return full; }catch(e){}\n"
    "  }\n"
    "  return meoRelPath(container, sample) || tag;\n"
    "}\n"
    "function meoAnalyzeTable(table){\n"
    "  var rows=table.querySelectorAll('tbody tr.el-table__row, tbody tr');\n"
    "  if(!rows.length) rows=table.querySelectorAll('tr');\n"
    "  var dataRows=Array.from(rows).filter(function(r){\n"
    "    if(r.querySelector('th') && !r.querySelector('td')) return false;\n"
    "    return !!r.querySelector('td');\n"
    "  });\n"
    "  // 选内容更完整的样例行（避免首行大量 '-' 影响判断链接列）\n"
    "  var sample=dataRows[0]||rows[0];\n"
    "  var bestScore=-1;\n"
    "  dataRows.slice(0,8).forEach(function(r){\n"
    "    var t=String(r.textContent||'').replace(/\\s+/g,' ').trim();\n"
    "    var score=t.length;\n"
    "    if(r.querySelector('a[href]')) score+=20;\n"
    "    if((t.match(/-/g)||[]).length>=3) score-=15;\n"
    "    if(score>bestScore){ bestScore=score; sample=r; }\n"
    "  });\n"
    "  var heads=meoTableHeaderLabels(table);\n"
    "  var fields=meoBuildTableFields(sample, heads);\n"
    "  var rowPath='tr';\n"
    "  if(table.querySelector('tbody tr.el-table__row')) rowPath='tbody tr.el-table__row';\n"
    "  else if(table.querySelector('tbody tr')) rowPath='tbody tr';\n"
    "  var c={\n"
    "    type:'table', title:'表格', structureType:'table',\n"
    "    containerPath:meoCssPath(table),\n"
    "    rowPath:rowPath,\n"
    "    estimatedRows:dataRows.length||rows.length,\n"
    "    fields:fields,\n"
    "    columns:fields.map(function(f){return f.name;}),\n"
    "    sampleText: sample?String(sample.textContent||'').replace(/\\s+/g,' ').trim().slice(0,80):''\n"
    "  };\n"
    "  return meoScoreCandidate(c, table, dataRows);\n"
    "}\n"
    "function meoAnalyzeList(list){\n"
    "  var items=Array.from(list.children).filter(function(c){return c.tagName&&c.tagName.toLowerCase()==='li';});\n"
    "  if(items.length<2) return null;\n"
    "  var fields=meoInferFields(items[0]);\n"
    "  var c={\n"
    "    type:'list', title:'列表', structureType:'list',\n"
    "    containerPath:meoCssPath(list), rowPath:':scope > li',\n"
    "    estimatedRows:items.length, fields:fields,\n"
    "    columns:fields.map(function(f){return f.name;}),\n"
    "    sampleText:String(items[0].textContent||'').replace(/\\s+/g,' ').trim().slice(0,80)\n"
    "  };\n"
    "  return meoScoreCandidate(c, list, items);\n"
    "}\n"
    "function meoFindCardGroups(root){\n"
    "  var best=[];\n"
    "  var seen={};\n"
    "  function pushGroup(parent, items, scoreBonus){\n"
    "    if(!parent||!items||items.length<3) return;\n"
    "    var key='';\n"
    "    try{ key=meoCssPath(parent)+'|'+meoFp(items[0])+'|'+items.length; }catch(e){ key=String(items.length); }\n"
    "    if(seen[key]) return; seen[key]=1;\n"
    "    var score=items.length*2 + meoItemScore(items[0])*3 + (scoreBonus||0);\n"
    "    if(parent.querySelector && parent.querySelector('a[href]')) score+=5;\n"
    "    // 明确的列表容器加权\n"
    "    var blob=String(parent.id||'')+' '+Array.from(parent.classList||[]).join(' ');\n"
    "    if(/list|result|search|company| ent |card/i.test(blob)) score+=12;\n"
    "    if(items[0].querySelector && items[0].querySelector('.companyName,[class*=\"companyName\"],.credit-code')) score+=18;\n"
    "    best.push({parent:parent, items:items, score:score});\n"
    "  }\n"
    "  // Pass A：按业务 class 快速捞循环卡（企知道 company-card-wrapper 等）\n"
    "  var hintSel='[class*=\"company-card\"],[class*=\"card-wrapper\"],[class*=\"result-item\"],[class*=\"search-item\"],[class*=\"list-item\"],[class*=\"product-item\"],[class*=\"goods-item\"],[class*=\"news-item\"],[class*=\"article-item\"],[class*=\"ent-item\"]';\n"
    "  try{\n"
    "    var hinted=Array.from((root||document).querySelectorAll(hintSel)).slice(0,400);\n"
    "    var byParent={};\n"
    "    hinted.forEach(function(el){\n"
    "      var p=el.parentElement; if(!p) return;\n"
    "      var fp=meoFp(el); if(!fp) return;\n"
    "      if(meoItemScore(el)<2) return;\n"
    "      var pk;\n"
    "      try{ pk=meoCssPath(p)+'@@'+fp; }catch(e){ pk=fp; }\n"
    "      if(!byParent[pk]) byParent[pk]={parent:p, items:[]};\n"
    "      byParent[pk].items.push(el);\n"
    "    });\n"
    "    Object.keys(byParent).forEach(function(k){\n"
    "      var g=byParent[k];\n"
    "      pushGroup(g.parent, g.items, 20);\n"
    "    });\n"
    "  }catch(e){}\n"
    "  // Pass B：同构子节点扫描（提高上限，覆盖重 DOM 页面）\n"
    "  var nodes=(root||document).querySelectorAll('*');\n"
    "  var limit=Math.min(nodes.length, 5000);\n"
    "  for(var i=0;i<limit;i++){\n"
    "    var parent=nodes[i];\n"
    "    if(!parent||!parent.children||parent.children.length<3) continue;\n"
    "    var tag=parent.tagName.toLowerCase();\n"
    "    if(['table','thead','tbody','tr','select','svg','script','style','ul','ol'].indexOf(tag)>=0) continue;\n"
    "    var groups={};\n"
    "    Array.from(parent.children).forEach(function(ch){\n"
    "      var fp=meoFp(ch);\n"
    "      if(!fp) return;\n"
    "      if(meoItemScore(ch)<2) return;\n"
    "      if(!groups[fp]) groups[fp]=[];\n"
    "      groups[fp].push(ch);\n"
    "    });\n"
    "    Object.keys(groups).forEach(function(fp){\n"
    "      pushGroup(parent, groups[fp], 0);\n"
    "    });\n"
    "  }\n"
    "  best.sort(function(a,b){ return b.score-a.score; });\n"
    "  return best;\n"
    "}\n"
    "function meoAnalyzeCards(parent, items){\n"
    "  var sample=items[0];\n"
    "  var fields=meoInferFields(sample);\n"
    "  var rowPath=meoRowSelector(parent, sample);\n"
    "  var c={\n"
    "    type:'cards', title:'卡片列表', structureType:'cards',\n"
    "    containerPath:meoCssPath(parent),\n"
    "    rowPath:rowPath,\n"
    "    estimatedRows:items.length,\n"
    "    fields:fields,\n"
    "    columns:fields.map(function(f){return f.name;}),\n"
    "    sampleText:String(sample.textContent||'').replace(/\\s+/g,' ').trim().slice(0,80)\n"
    "  };\n"
    "  return meoScoreCandidate(c, parent, items);\n"
    "}\n"
    "function meoNavPenalty(el){\n"
    "  if(!el||el.nodeType!==1) return 0;\n"
    "  var penalty=0;\n"
    "  try{\n"
    "    if(el.closest('nav,header,footer,aside,[role=\"navigation\"],[role=\"banner\"],[role=\"contentinfo\"]')) penalty-=42;\n"
    "  }catch(e){}\n"
    "  function blob(node){\n"
    "    if(!node) return '';\n"
    "    return String(node.id||'')+' '+Array.from(node.classList||[]).join(' ')+' '+String(node.getAttribute&&node.getAttribute('role')||'');\n"
    "  }\n"
    "  var s=blob(el).toLowerCase();\n"
    "  if(/\\b(nav|menu|navbar|sidebar|footer|breadcrumb|tabbar|toolbar|pagination|pager|related|recommend|hot[-_]?rank|tag[-_]?cloud)\\b/.test(s)) penalty-=28;\n"
    "  var p=el.parentElement;\n"
    "  for(var i=0;i<5&&p;i++){\n"
    "    var ps=blob(p).toLowerCase();\n"
    "    if(/\\b(nav|menu|navbar|sidebar|footer|breadcrumb|toolbar)\\b/.test(ps)){ penalty-=16; break; }\n"
    "    p=p.parentElement;\n"
    "  }\n"
    "  return penalty;\n"
    "}\n"
    "function meoMainBonus(el){\n"
    "  if(!el||el.nodeType!==1) return 0;\n"
    "  try{\n"
    "    if(el.closest('main,article,[role=\"main\"],#content,#main,#app-content,.content,.main,.post-list,.news-list,.article-list,.list-wrapper,[id*=\"listBox\"],[id*=\"searchCompany\"],[class*=\"company-card\"]')) return 20;\n"
    "  }catch(e){}\n"
    "  var rect=el.getBoundingClientRect();\n"
    "  var docH=Math.max(document.body?document.body.scrollHeight:0, document.documentElement.scrollHeight, 1);\n"
    "  var midY=(rect.top+(window.scrollY||0)+rect.height/2)/docH;\n"
    "  if(midY>0.12 && midY<0.78) return 10;\n"
    "  if(midY<0.07 || midY>0.92) return -12;\n"
    "  return 0;\n"
    "}\n"
    "function meoItemContentSignals(items){\n"
    "  var out={avgLen:0, shortRatio:0, uniqueHrefs:0, withTitle:0, withTime:0, withImg:0, withDesc:0, selfLink:0};\n"
    "  if(!items||!items.length) return out;\n"
    "  var sample=items.slice(0, Math.min(10, items.length));\n"
    "  var hrefSet={}; var short=0; var totalLen=0;\n"
    "  sample.forEach(function(it){\n"
    "    var t=String(it.textContent||'').replace(/\\s+/g,' ').trim();\n"
    "    totalLen+=t.length;\n"
    "    if(t.length>0 && t.length<18) short++;\n"
    "    var selfA=null;\n"
    "    try{ if(it.matches && it.matches('a[href]')) selfA=it; }catch(e){}\n"
    "    if(!selfA && it.tagName && it.tagName.toLowerCase()==='a' && it.getAttribute('href')) selfA=it;\n"
    "    var a=selfA || (it.querySelector && it.querySelector('a[href]'));\n"
    "    if(a){\n"
    "      var href='';\n"
    "      try{ href=new URL(a.getAttribute('href'), location.href).pathname; }catch(e){ href=a.getAttribute('href')||''; }\n"
    "      if(href) hrefSet[href]=1;\n"
    "      if(selfA) out.selfLink++;\n"
    "    }\n"
    "    if(it.querySelector && it.querySelector('h1,h2,h3,h4,h5,h6,[class*=\"title\"]')) out.withTitle++;\n"
    "    if(it.querySelector && it.querySelector('time,[datetime],[class*=\"time\"],[class*=\"date\"],[class*=\"gray-400\"]')) out.withTime++;\n"
    "    if(it.querySelector && it.querySelector('img[src]')) out.withImg++;\n"
    "    if(it.querySelector && it.querySelector('p,[class*=\"desc\"],[class*=\"summary\"],[class*=\"line-clamp\"]')) out.withDesc++;\n"
    "  });\n"
    "  out.avgLen=totalLen/sample.length;\n"
    "  out.shortRatio=short/sample.length;\n"
    "  out.uniqueHrefs=Object.keys(hrefSet).length;\n"
    "  return out;\n"
    "}\n"
    "function meoScoreCandidate(c, container, items){\n"
    "  if(!c) return c;\n"
    "  var score=0;\n"
    "  var n=c.estimatedRows||0;\n"
    "  if(n>=5 && n<=50) score+=18;\n"
    "  else if(n>=3 && n<=80) score+=10;\n"
    "  else if(n>120) score-=10;\n"
    "  else if(n<3) score-=12;\n"
    "  score+=meoNavPenalty(container);\n"
    "  score+=meoMainBonus(container);\n"
    "  var fields=c.fields||[];\n"
    "  score+=Math.min(fields.length,6)*4;\n"
    "  var hasHref=fields.some(function(f){return f && (f.kind==='href' || f.name==='链接');});\n"
    "  var hasTitle=fields.some(function(f){return f && f.name==='标题';});\n"
    "  var hasTime=fields.some(function(f){return f && f.name==='时间';});\n"
    "  var hasDesc=fields.some(function(f){return f && f.name==='摘要';});\n"
    "  var hasImg=fields.some(function(f){return f && (f.kind==='src' || f.name==='图片');});\n"
    "  if(hasHref) score+=12;\n"
    "  if(hasTitle) score+=10;\n"
    "  if(hasTime) score+=8;\n"
    "  if(hasDesc) score+=8;\n"
    "  if(hasImg) score+=5;\n"
    "  if(fields.some(function(f){return f && f.name==='价格';})) score+=16;\n"
    "  if(fields.some(function(f){return f && f.name==='付款人数';})) score+=10;\n"
    "  if(fields.some(function(f){return f && f.name==='店名';})) score+=8;\n"
    "  if(fields.some(function(f){return f && f.name==='企业名称';})) score+=18;\n"
    "  if(fields.some(function(f){return f && f.name==='统一社会信用代码';})) score+=10;\n"
    "  if(fields.some(function(f){return f && (f.name==='法定代表人'||f.name==='注册资本');})) score+=6;\n"
    "  var sig=meoItemContentSignals(items);\n"
    "  if(sig.avgLen>=24 && sig.avgLen<=2000) score+=12;\n"
    "  else if(sig.avgLen>=12 && sig.avgLen<24) score+=4;\n"
    "  else if(sig.avgLen>0 && sig.avgLen<12) score-=14;\n"
    "  if(sig.shortRatio>0.7) score-=18;\n"
    "  if(sig.uniqueHrefs>=Math.min(3, Math.max(1, Math.floor((items&&items.length)||0)*0.5))) score+=14;\n"
    "  else if(sig.uniqueHrefs<=1 && n>=4) score-=12;\n"
    "  if(sig.withTitle>=Math.ceil(Math.min(items.length||0,10)*0.5)) score+=8;\n"
    "  if(sig.withTime>=2) score+=6;\n"
    "  if(sig.withDesc>=2) score+=6;\n"
    "  if(sig.selfLink>=Math.ceil(Math.min(items.length||0,10)*0.6)) score+=6;\n"
    "  if(c.type==='table'){\n"
    "    if(container && container.querySelector && container.querySelector('thead th')) score+=12;\n"
    "    var cols=(c.columns&&c.columns.length)||0;\n"
    "    if(cols>=3) score+=8;\n"
    "    else if(cols===1) score-=6;\n"
    "  }\n"
    "  if(c.type==='cards') score+=3;\n"
    "  if(c.type==='list' && sig.avgLen<20 && !hasDesc && !hasTime) score-=8;\n"
    "  // 过宽的整页壳：子节点很多但 item 文本像导航\n"
    "  if(container && container.children && container.children.length>40 && sig.avgLen<30) score-=10;\n"
    "  c.score=Math.round(score);\n"
    "  c.scoreSignals={avgLen:Math.round(sig.avgLen), uniqueHrefs:sig.uniqueHrefs, shortRatio:Math.round(sig.shortRatio*100)/100};\n"
    "  return c;\n"
    "}\n"
    "function meoRankCandidates(list){\n"
    "  var out=(list||[]).slice();\n"
    "  out.sort(function(a,b){\n"
    "    var ds=(b.score||0)-(a.score||0);\n"
    "    if(ds) return ds;\n"
    "    return (b.estimatedRows||0)-(a.estimatedRows||0);\n"
    "  });\n"
    "  if(!out.length) return out;\n"
    "  var best=out[0];\n"
    "  var second=out.length>1?out[1]:null;\n"
    "  var bestScore=best.score||0;\n"
    "  var margin=second? (bestScore-(second.score||0)) : 999;\n"
    "  best.recommended=true;\n"
    "  // 置信度：分数够高，且显著优于第二名（或仅有一个）\n"
    "  best.confident = bestScore>=36 && margin>=8;\n"
    "  if(bestScore>=48 && margin>=5) best.confident=true;\n"
    "  if(out.length===1 && bestScore>=28) best.confident=true;\n"
    "  out.forEach(function(c,i){\n"
    "    if(!c) return;\n"
    "    if(c.type==='cards') c.title='卡片列表 '+(i+1)+'（'+(c.estimatedRows||0)+'项）';\n"
    "    else if(c.type==='list') c.title='列表 '+(i+1)+'（'+(c.estimatedRows||0)+'项）';\n"
    "    else if(c.type==='table') c.title='表格 '+(i+1)+'（'+(c.estimatedRows||0)+'行）';\n"
    "    if(c.recommended) c.title='推荐 · '+c.title;\n"
    "  });\n"
    "  return out;\n"
    "}\n"
    "function meoAnalyzeFromNode(node){\n"
    "  if(!node||node.nodeType!==1) return null;\n"
    "  var tag=node.tagName.toLowerCase();\n"
    "  if(tag==='table') return meoAnalyzeTable(node);\n"
    "  var table=node.closest ? node.closest('table') : null;\n"
    "  if(table) return meoAnalyzeTable(table);\n"
    "  if(tag==='ul'||tag==='ol') return meoAnalyzeList(node);\n"
    "  var list=node.closest ? node.closest('ul,ol') : null;\n"
    "  if(list) return meoAnalyzeList(list);\n"
    "  var cur=node;\n"
    "  for(var up=0; up<6 && cur && cur.parentElement; up++){\n"
    "    var parent=cur.parentElement;\n"
    "    var fp=meoFp(cur);\n"
    "    if(fp){\n"
    "      var sibs=Array.from(parent.children).filter(function(c){ return meoFp(c)===fp && meoItemScore(c)>=2; });\n"
    "      if(sibs.length>=3) return meoAnalyzeCards(parent, sibs);\n"
    "    }\n"
    "    cur=parent;\n"
    "  }\n"
    "  var groups=meoFindCardGroups(node);\n"
    "  if(groups.length) return meoAnalyzeCards(groups[0].parent, groups[0].items);\n"
    "  var fields=meoInferFields(node);\n"
    "  var scalar={\n"
    "    type:'scalar', title:'单一区域', structureType:'scalar',\n"
    "    containerPath:meoCssPath(node), rowPath:'',\n"
    "    estimatedRows:1, fields:fields,\n"
    "    columns:fields.map(function(f){return f.name;}),\n"
    "    sampleText:String(node.textContent||'').replace(/\\s+/g,' ').trim().slice(0,80)\n"
    "  };\n"
    "  return meoScoreCandidate(scalar, node, [node]);\n"
    "}\n"
    "function meoDetectPageCandidates(){\n"
    "  var out=[], seen={};\n"
    "  function add(c){\n"
    "    if(!c||!c.containerPath) return;\n"
    "    var key=c.containerPath+'|'+c.rowPath;\n"
    "    if(seen[key]) return; seen[key]=1;\n"
    "    out.push(c);\n"
    "  }\n"
    "  Array.from(document.querySelectorAll('table')).slice(0,8).forEach(function(t){ add(meoAnalyzeTable(t)); });\n"
    "  Array.from(document.querySelectorAll('ul,ol')).slice(0,10).forEach(function(l){\n"
    "    var a=meoAnalyzeList(l); if(a&&a.estimatedRows>=3) add(a);\n"
    "  });\n"
    "  meoFindCardGroups(document.body).slice(0,12).forEach(function(g){\n"
    "    add(meoAnalyzeCards(g.parent, g.items));\n"
    "  });\n"
    "  return meoRankCandidates(out).slice(0,16);\n"
    "}\n";
}

+ (void)detectCandidatesInWebView:(WKWebView *)webView
                       completion:(void (^)(NSArray<NSDictionary *> *candidates))completion {
    if (!webView) {
        if (completion) completion(@[]);
        return;
    }
    NSString *js = [NSString stringWithFormat:@"(function(){\n%@\nreturn meoDetectPageCandidates();\n})();",
                    [self structureHelpersJavaScript]];
    [webView evaluateJavaScript:js completionHandler:^(id result, NSError *error) {
        (void)error;
        NSArray *arr = [result isKindOfClass:[NSArray class]] ? result : @[];
        if (completion) completion(arr);
    }];
}

+ (void)analyzeContainerInWebView:(WKWebView *)webView
                    containerPath:(NSString *)containerPath
                       completion:(void (^)(NSDictionary * _Nullable analysis, NSError * _Nullable error))completion {
    if (!webView) {
        if (completion) {
            completion(nil, [NSError errorWithDomain:@"BrowserScraper" code:20
                                           userInfo:@{NSLocalizedDescriptionKey:@"无 WebView"}]);
        }
        return;
    }
    NSString *pathJSON = [self jsonStringLiteral:containerPath];
    NSString *js = [NSString stringWithFormat:
                    @"(function(){\n%@\n"
                     "  var path=%@;\n"
                     "  var node=path?document.querySelector(path):null;\n"
                     "  if(!node) return { error:'找不到选中节点' };\n"
                     "  return meoAnalyzeFromNode(node);\n"
                     "})();",
                    [self structureHelpersJavaScript], pathJSON];
    [webView evaluateJavaScript:js completionHandler:^(id result, NSError *error) {
        if (error) {
            if (completion) completion(nil, error);
            return;
        }
        if (![result isKindOfClass:[NSDictionary class]]) {
            if (completion) {
                completion(nil, [NSError errorWithDomain:@"BrowserScraper" code:21
                                               userInfo:@{NSLocalizedDescriptionKey:@"分析结果无效"}]);
            }
            return;
        }
        NSDictionary *dict = (NSDictionary *)result;
        if ([dict[@"error"] isKindOfClass:[NSString class]]) {
            if (completion) {
                completion(nil, [NSError errorWithDomain:@"BrowserScraper" code:22
                                               userInfo:@{NSLocalizedDescriptionKey: dict[@"error"]}]);
            }
            return;
        }
        if (completion) completion(dict, nil);
    }];
}

+ (void)extractRowsInWebView:(WKWebView *)webView
                        mode:(NSString *)mode
               containerPath:(NSString *)containerPath
                     rowPath:(NSString *)rowPath
                      fields:(NSArray<NSDictionary *> *)fields
               absoluteURLs:(BOOL)absoluteURLs
                     maxRows:(NSInteger)maxRows
                  completion:(void (^)(NSArray<NSDictionary *> *rows, NSError * _Nullable error))completion {
    if (!webView) {
        if (completion) {
            completion(@[], [NSError errorWithDomain:@"BrowserScraper" code:10 userInfo:@{NSLocalizedDescriptionKey:@"无 WebView"}]);
        }
        return;
    }
    NSError *jsonError = nil;
    id fieldsJSONObject = fields ?: @[];
    if (![NSJSONSerialization isValidJSONObject:fieldsJSONObject]) {
        NSMutableArray *cleaned = [NSMutableArray array];
        for (id item in [fields isKindOfClass:[NSArray class]] ? fields : @[]) {
            if (![item isKindOfClass:[NSDictionary class]]) continue;
            NSMutableDictionary *d = [NSMutableDictionary dictionary];
            [(NSDictionary *)item enumerateKeysAndObjectsUsingBlock:^(id key, id obj, BOOL *stop) {
                (void)stop;
                if ([obj isKindOfClass:[NSNull class]]) return;
                if ([obj isKindOfClass:[NSString class]] || [obj isKindOfClass:[NSNumber class]] ||
                    [obj isKindOfClass:[NSArray class]] || [obj isKindOfClass:[NSDictionary class]]) {
                    d[key] = obj;
                }
            }];
            [cleaned addObject:d];
        }
        fieldsJSONObject = cleaned;
    }
    NSData *fieldsData = [NSJSONSerialization dataWithJSONObject:fieldsJSONObject options:0 error:&jsonError];
    if (!fieldsData) {
        if (completion) completion(@[], jsonError);
        return;
    }
    NSString *fieldsJSON = [[NSString alloc] initWithData:fieldsData encoding:NSUTF8StringEncoding];
    NSString *containerJSON = [self jsonStringLiteral:containerPath];
    NSString *rowJSON = [self jsonStringLiteral:rowPath];
    NSString *modeJSON = [self jsonStringLiteral:mode ?: @"table"];

    NSString *js = [NSString stringWithFormat:
        @"(function(){\n"
         "  var mode=%@, containerPath=%@, rowPath=%@, fields=%@, absoluteURLs=%@, maxRows=%ld;\n"
         "  function q(root, sel){ try { return sel ? root.querySelector(sel) : root; } catch(e){ return null; } }\n"
         "  function qa(root, sel){\n"
         "    try {\n"
         "      if(!sel) return [];\n"
         "      if(sel.indexOf(':scope')===0){\n"
         "        var rest=sel.replace(/^:scope\\s*>\\s*/,'').trim();\n"
         "        return Array.from(root.children).filter(function(c){\n"
         "          try { return c.matches(rest); } catch(e){ return c.tagName && c.tagName.toLowerCase()===rest; }\n"
         "        });\n"
         "      }\n"
         "      return Array.from(root.querySelectorAll(sel));\n"
         "    } catch(e){ return []; }\n"
         "  }\n"
         "  function abs(u){ try { return absoluteURLs ? new URL(u, location.href).href : u; } catch(e){ return u; } }\n"
         "  function val(el, field){\n"
         "    if(!el) return '';\n"
         "    var kind = field.kind || 'text';\n"
         "    if(kind==='joinPrice'){\n"
         "      var parts=String(field.path||'').split('||');\n"
         "      var a=parts[0]?q(el, parts[0].trim()):null;\n"
         "      var b=parts[1]?q(el, parts[1].trim()):null;\n"
         "      return String((a&&a.textContent)||'').replace(/\\s+/g,'').trim()+String((b&&b.textContent)||'').replace(/\\s+/g,'').trim();\n"
         "    }\n"
         "    var target = field.path ? q(el, field.path) : el;\n"
         "    if(!target) return '';\n"
         "    if(kind==='href'){ var a = target.closest ? (target.closest('a')||target) : target; var h=a.getAttribute && a.getAttribute('href'); return h?abs(h):''; }\n"
         "    if(kind==='src'){ var s=target.getAttribute && target.getAttribute('src'); return s?abs(s):''; }\n"
         "    if(kind==='attribute'){ return (target.getAttribute && target.getAttribute(field.attribute||'')) || ''; }\n"
         "    if(kind==='html'){ return String(target.innerHTML||'').slice(0,8000); }\n"
         "    var text=String(target.textContent||'').replace(/\\s+/g,' ').trim();\n"
         "    // 价格容器：去空格与货币符号，得到 369 / 7.8\n"
         "    if(field.name==='价格') text=String(target.textContent||'').replace(/\\s+/g,'').replace(/[¥￥$€£]/g,'').trim();\n"
         "    return text;\n"
         "  }\n"
         "  var container = containerPath ? document.querySelector(containerPath) : document.body;\n"
         "  if(!container) return { error: '找不到容器' };\n"
         "  var rows=[];\n"
         "  if(mode==='scalar'){\n"
         "    var obj={};\n"
         "    fields.forEach(function(f){ if(f.enabled===false) return; obj[f.name||f.id]=val(container,f); });\n"
         "    rows.push(obj);\n"
         "    return { rows: rows };\n"
         "  }\n"
         "  var nodes = rowPath ? qa(container, rowPath) : [container];\n"
         "  if(rowPath==='tr' || rowPath==='tbody tr'){\n"
         "    if(nodes[0] && nodes[0].querySelector && nodes[0].querySelector('th') && !nodes[0].querySelector('td')) nodes=nodes.slice(1);\n"
         "  }\n"
         "  nodes.slice(0, maxRows).forEach(function(node){\n"
         "    var obj={};\n"
         "    var empty=true;\n"
         "    fields.forEach(function(f){\n"
         "      if(f.enabled===false) return;\n"
         "      var v=val(node,f);\n"
         "      obj[f.name||f.id]=v;\n"
         "      if(String(v).trim()) empty=false;\n"
         "    });\n"
         "    if(!empty) rows.push(obj);\n"
         "  });\n"
         "  return { rows: rows };\n"
         "})();",
        modeJSON, containerJSON, rowJSON, fieldsJSON, absoluteURLs ? @"true" : @"false", (long)MAX(1, maxRows)];

    [webView evaluateJavaScript:js completionHandler:^(id result, NSError *error) {
        if (error) {
            if (completion) completion(@[], error);
            return;
        }
        if (![result isKindOfClass:[NSDictionary class]]) {
            if (completion) completion(@[], [NSError errorWithDomain:@"BrowserScraper" code:11 userInfo:@{NSLocalizedDescriptionKey:@"抽取结果无效"}]);
            return;
        }
        NSDictionary *dict = (NSDictionary *)result;
        if ([dict[@"error"] isKindOfClass:[NSString class]]) {
            if (completion) {
                completion(@[], [NSError errorWithDomain:@"BrowserScraper" code:12 userInfo:@{NSLocalizedDescriptionKey: dict[@"error"]}]);
            }
            return;
        }
        NSArray *rows = [dict[@"rows"] isKindOfClass:[NSArray class]] ? dict[@"rows"] : @[];
        if (completion) completion(rows, nil);
    }];
}

+ (NSString *)waitForSelectorJavaScript:(NSString *)selector timeoutMs:(NSInteger)timeoutMs {
    NSString *selJSON = [self jsonStringLiteral:selector];
    return [NSString stringWithFormat:
            @"(function(){ return new Promise(function(resolve){\n"
             "  var sel=%@, timeout=%ld, start=Date.now();\n"
             "  if(!sel){ resolve(true); return; }\n"
             "  function check(){ if(document.querySelector(sel)){ resolve(true); return; }\n"
             "    if(Date.now()-start>=timeout){ resolve(false); return; }\n"
             "    setTimeout(check, 120); }\n"
             "  check();\n"
             "}); })()", selJSON, (long)MAX(0, timeoutMs)];
}

/// 翻页控件启发式（优先下一页按钮 / Load More，其次页码，最后无限滚动）。
+ (NSString *)paginationHelpersJavaScript {
    return @
    "function meoEsc(v){ if(window.CSS&&CSS.escape) return CSS.escape(v); return String(v).replace(/[^a-zA-Z0-9_-]/g,'\\\\$&'); }\n"
    "function meoCssPath(el){\n"
    "  if(!el||el.nodeType!==1) return '';\n"
    "  if(el.id){ var s='#'+meoEsc(el.id); try{ if(document.querySelectorAll(s).length===1) return s; }catch(e){} }\n"
    "  var parts=[], node=el;\n"
    "  while(node&&node.nodeType===1&&node!==document.documentElement&&parts.length<7){\n"
    "    var part=node.tagName.toLowerCase();\n"
    "    var cls=Array.from(node.classList||[]).filter(function(c){return c&&!/^(active|hover|selected|open|show|is-|js-|disabled|current)/i.test(c);}).slice(0,2);\n"
    "    if(cls.length) part+='.'+cls.map(meoEsc).join('.');\n"
    "    var p=node.parentElement;\n"
    "    if(p){\n"
    "      var sib=Array.from(p.children).filter(function(c){return c.tagName===node.tagName;});\n"
    "      if(sib.length>1) part+=':nth-of-type('+(sib.indexOf(node)+1)+')';\n"
    "    }\n"
    "  parts.unshift(part); node=p;\n"
    "  }\n"
    "  return parts.join(' > ');\n"
    "}\n"
    "function meoVisible(el){\n"
    "  if(!el||el.nodeType!==1) return false;\n"
    "  var st=window.getComputedStyle(el);\n"
    "  if(!st||st.display==='none'||st.visibility==='hidden'||Number(st.opacity)===0) return false;\n"
    "  var r=el.getBoundingClientRect();\n"
    "  return r.width>2 && r.height>2;\n"
    "}\n"
    "function meoNormText(el){\n"
    "  return ((el&&(el.innerText||el.textContent))||'').replace(/\\s+/g,' ').trim();\n"
    "}\n"
    "function meoNearRoots(anchorPath){\n"
    "  var roots=[], seen=new Set();\n"
    "  function add(n){ if(!n||n.nodeType!==1||seen.has(n)) return; seen.add(n); roots.push(n); }\n"
    "  var anchor=null;\n"
    "  try{ if(anchorPath) anchor=document.querySelector(anchorPath); }catch(e){}\n"
    "  if(anchor){\n"
    "    add(anchor);\n"
    "    var p=anchor.parentElement, depth=0;\n"
    "    while(p&&depth<6){\n"
    "      add(p);\n"
    "      Array.from(p.children||[]).forEach(function(c){ if(c!==anchor) add(c); });\n"
    "      p=p.parentElement; depth++;\n"
    "    }\n"
    "  }\n"
    "  add(document.body);\n"
    "  return roots;\n"
    "}\n"
    "function meoQueryInRoots(roots, sel){\n"
    "  var out=[], seen=new Set();\n"
    "  roots.forEach(function(root){\n"
    "    try{\n"
    "      Array.from(root.querySelectorAll(sel)).forEach(function(el){\n"
    "        if(seen.has(el)) return; seen.add(el); out.push(el);\n"
    "      });\n"
    "    }catch(e){}\n"
    "  });\n"
    "  return out;\n"
    "}\n"
    "function meoStableSelFor(el, preferred){\n"
    "  var prefs=preferred||[];\n"
    "  for(var i=0;i<prefs.length;i++){\n"
    "    var s=prefs[i];\n"
    "    try{\n"
    "      var nodes=document.querySelectorAll(s);\n"
    "      if(nodes.length===1 && nodes[0]===el) return s;\n"
    "      if(el.matches && el.matches(s) && nodes.length===1) return s;\n"
    "    }catch(e){}\n"
    "  }\n"
    "  return meoCssPath(el);\n"
    "}\n"
    "function meoScoreNextButton(el){\n"
    "  if(!meoVisible(el)) return 0;\n"
    "  var tag=el.tagName.toLowerCase();\n"
    "  if(['script','style','svg','input'].indexOf(tag)>=0) return 0;\n"
    "  var t=meoNormText(el);\n"
    "  if(t.length>24) return 0;\n"
    "  // 纯数字是页码，不是下一页\n"
    "  if(/^\\d{1,4}$/.test(t)) return 0;\n"
    "  if(/^[\\.…]+$/.test(t)) return 0;\n"
    "  var aria=((el.getAttribute('aria-label')||'')+' '+(el.getAttribute('title')||'')+' '+(el.getAttribute('rel')||'')).toLowerCase();\n"
    "  var cls=(el.className&&String(el.className))||'';\n"
    "  var parentCls='';\n"
    "  try{\n"
    "    var wrap=el.closest && el.closest('li,button,a,span,div');\n"
    "    if(wrap) parentCls=(wrap.className&&String(wrap.className))||'';\n"
    "    // bootstrap-table: li.page-next > a\n"
    "    var pn=el.closest && el.closest('li.page-next, .page-next, .next, .btn-next');\n"
    "    if(pn) parentCls+=' page-next';\n"
    "  }catch(e){}\n"
    "  var allCls=cls+' '+parentCls;\n"
    "  var score=0;\n"
    "  if(/^(下一页|下页|后一页|下一張|next|>|›|»|→|››)$/i.test(t)) score+=70;\n"
    "  else if(/(下一页|下页|后一页|next\\s*page|^next$)/i.test(t)) score+=55;\n"
    "  if(/(下一页|下页|next)/i.test(aria)) score+=40;\n"
    "  if(/\\b(btn-next|next-page|page-next|pagination__next|pager__next|el-pagination__next|ant-pagination-next)\\b/i.test(allCls)) score+=60;\n"
    "  try{\n"
    "    if(el.matches('.el-pagination .btn-next, button.btn-next, .ant-pagination-next, li.ant-pagination-next, li.page-next, li.page-next a, .pagination .page-next a, .pagination .next, a.next, button.next')) score+=55;\n"
    "  }catch(e){}\n"
    "  var disabledHost=el;\n"
    "  try{ if(el.closest) disabledHost=el.closest('li,button,a')||el; }catch(e){}\n"
    "  if((disabledHost.getAttribute&&disabledHost.getAttribute('aria-disabled')==='true') || disabledHost.classList.contains('disabled') || disabledHost.disabled || disabledHost.classList.contains('is-disabled')) score-=90;\n"
    "  if(/上一页|上页|prev|previous|首页|尾页|跳转/i.test(t) && !/下一页|下页|next/i.test(t)) score-=80;\n"
    "  if(/\\b(page-pre|page-prev|page-first|page-last|jumpto)\\b/i.test(allCls) && !/\\bpage-next\\b/i.test(allCls)) score-=80;\n"
    "  return score;\n"
    "}\n"
    "function meoScoreLoadMore(el){\n"
    "  if(!meoVisible(el)) return 0;\n"
    "  var t=meoNormText(el);\n"
    "  if(t.length>40) return 0;\n"
    "  var aria=((el.getAttribute('aria-label')||'')+' '+(el.getAttribute('title')||'')).toLowerCase();\n"
    "  var cls=(el.className&&String(el.className))||'';\n"
    "  var score=0;\n"
    "  if(/(加载更多|查看更多|显示更多|更多结果|load\\s*more|show\\s*more|see\\s*more|view\\s*more)/i.test(t)) score+=60;\n"
    "  if(/(加载更多|load\\s*more|show\\s*more)/i.test(aria)) score+=45;\n"
    "  if(/\\b(load[-_]?more|show[-_]?more|more[-_]?btn|btn[-_]?more)\\b/i.test(cls)) score+=50;\n"
    "  if(el.disabled || el.getAttribute('aria-disabled')==='true') score-=80;\n"
    "  return score;\n"
    "}\n"
    "function meoFindPageNumberGroup(roots){\n"
    "  // 优先精确数字页码；避免宽泛的 .pagination li a（会混入上一页/下一页）\n"
    "  var groupSels=[\n"
    "    '.el-pagination .el-pager li.number',\n"
    "    '.el-pager li.number',\n"
    "    '.ant-pagination-item',\n"
    "    'ul.pagination li.page-number',\n"
    "    '.pagination li.page-number a',\n"
    "    '.pagination li.page-number',\n"
    "    '.pagination .page-item .page-link',\n"
    "    'ul.pagination li.page-number a',\n"
    "    '[class*=\"pager\"] li.number',\n"
    "    'nav[aria-label*=\"pagination\"] a',\n"
    "    'nav[aria-label*=\"Pagination\"] a'\n"
    "  ];\n"
    "  var best=null;\n"
    "  groupSels.forEach(function(sel){\n"
    "    var nodes=meoQueryInRoots(roots, sel).filter(meoVisible);\n"
    "    var nums=nodes.filter(function(n){\n"
    "      var t=meoNormText(n);\n"
    "      if(!/^\\d{1,4}$/.test(t)) return false;\n"
    "      // 排除上一页/下一页/首页/尾页容器内的节点\n"
    "      try{\n"
    "        if(n.closest && n.closest('li.page-next, li.page-pre, li.page-prev, li.page-first, li.page-last, li.jumpto, .btn-next, .btn-prev')) return false;\n"
    "      }catch(e){}\n"
    "      return true;\n"
    "    });\n"
    "    if(nums.length<2) return;\n"
    "    var score=30+Math.min(35, nums.length*5);\n"
    "    if(/el-pager|ant-pagination-item|page-number/.test(sel)) score+=20;\n"
    "    if(!best || score>best.score) best={ type:'pageNumbers', selector:sel, score:score, reason:'页码组 '+sel+' ×'+nums.length, count:nums.length };\n"
    "  });\n"
    "  if(best) return best;\n"
    "  // 兜底：同一父节点下多个纯数字链接/按钮\n"
    "  var clickables=meoQueryInRoots(roots, 'a,button,li,span').filter(meoVisible);\n"
    "  var byParent={};\n"
    "  clickables.forEach(function(el){\n"
    "    var t=meoNormText(el);\n"
    "    if(!/^\\d{1,4}$/.test(t)) return;\n"
    "    var p=el.parentElement; if(!p) return;\n"
    "    var k=meoCssPath(p)||String(p);\n"
    "    if(!byParent[k]) byParent[k]={ parent:p, items:[] };\n"
    "    byParent[k].items.push(el);\n"
    "  });\n"
    "  Object.keys(byParent).forEach(function(k){\n"
    "    var g=byParent[k];\n"
    "    if(g.items.length<3) return;\n"
    "    var childSel=g.items[0].tagName.toLowerCase();\n"
    "    var cls=Array.from(g.items[0].classList||[]).filter(function(c){return c&&!/active|current|selected/i.test(c);}).slice(0,1);\n"
    "    if(cls.length) childSel+='.'+meoEsc(cls[0]);\n"
    "    var sel=meoCssPath(g.parent)+' > '+childSel;\n"
    "    try{ if(document.querySelectorAll(sel).length<2) sel=meoCssPath(g.parent)+' '+g.items[0].tagName.toLowerCase(); }catch(e){}\n"
    "    var score=28+Math.min(30, g.items.length*5);\n"
    "    if(!best || score>best.score) best={ type:'pageNumbers', selector:sel, score:score, reason:'邻近数字页码 ×'+g.items.length, count:g.items.length };\n"
    "  });\n"
    "  return best;\n"
    "}\n"
    "function meoDetectInfinite(roots, hasPagerUI){\n"
    "  if(hasPagerUI) return null;\n"
    "  var score=0, reason=[];\n"
    "  var markers=[\n"
    "    '[v-infinite-scroll]',\n"
    "    '[infinite-scroll-disabled]',\n"
    "    '.el-infinite-scroll',\n"
    "    '[class*=\"infinite-scroll\"]',\n"
    "    '[class*=\"InfiniteScroll\"]',\n"
    "    '.infinite-scroll-component',\n"
    "    '[data-infinite]',\n"
    "    '[data-testid*=\"infinite\"]'\n"
    "  ];\n"
    "  markers.forEach(function(sel){\n"
    "    if(meoQueryInRoots(roots, sel).length){ score+=45; reason.push(sel); }\n"
    "  });\n"
    "  var loadingTxt=meoQueryInRoots(roots, 'div,span,p,button').filter(function(el){\n"
    "    var t=meoNormText(el);\n"
    "    return t.length<20 && /(加载中|正在加载|loading\\.\\.\\.|load more)/i.test(t);\n"
    "  });\n"
    "  if(loadingTxt.length){ score+=18; reason.push('loading文案'); }\n"
    "  // 可滚动列表容器且明显高于视口\n"
    "  var scrollBoxes=meoQueryInRoots(roots, 'div,section,main,ul').filter(function(el){\n"
    "    var st=window.getComputedStyle(el);\n"
    "    if(!st) return false;\n"
    "    var oy=st.overflowY;\n"
    "    if(oy!=='auto' && oy!=='scroll') return false;\n"
    "    return el.scrollHeight > el.clientHeight + 80 && el.clientHeight > 120;\n"
    "  });\n"
    "  if(scrollBoxes.length){ score+=22; reason.push('可滚动容器'); }\n"
    "  if(score<50) return null;\n"
    "  return { type:'infiniteScroll', selector:'', score:score, reason:'滚动加载：'+(reason.join('、')||'启发式'), scrollStepPx:900, scrollSettleMs:800, pageDelayMs:500, maxPages:40 };\n"
    "}\n"
    "function meoDetectPagination(anchorPath){\n"
    "  var roots=meoNearRoots(anchorPath);\n"
    "  // 先扫明确的下一页控件（bootstrap-table / Element / Ant）\n"
    "  var nextPreferSels=['ul.pagination li.page-next a','.pagination li.page-next a','li.page-next a','.page-next a','.el-pagination .btn-next','button.btn-next','.ant-pagination-next','.pagination .next a','a.next','button.next'];\n"
    "  var nextCands=[];\n"
    "  nextPreferSels.forEach(function(sel){\n"
    "    meoQueryInRoots(roots, sel).forEach(function(el){\n"
    "      var s=meoScoreNextButton(el);\n"
    "      if(s<=0) return; // 禁用的下一页不采用\n"
    "      if(s<50) s=50; // 命中语义选择器保底\n"
    "      nextCands.push({ el:el, score:s, preferSel:sel });\n"
    "    });\n"
    "  });\n"
    "  meoQueryInRoots(roots, 'a,button,li').forEach(function(el){\n"
    "    var s=meoScoreNextButton(el);\n"
    "    if(s>=40) nextCands.push({ el:el, score:s, preferSel:null });\n"
    "  });\n"
    "  nextCands.sort(function(a,b){ return b.score-a.score; });\n"
    "  // 去重同一节点\n"
    "  var seenNext=new Set(), uniqNext=[];\n"
    "  nextCands.forEach(function(x){ if(seenNext.has(x.el)) return; seenNext.add(x.el); uniqNext.push(x); });\n"
    "  nextCands=uniqNext;\n"
    "  var loadCands=meoQueryInRoots(roots, 'a,button,div,span').map(function(el){\n"
    "    return { el:el, score:meoScoreLoadMore(el) };\n"
    "  }).filter(function(x){ return x.score>=40; }).sort(function(a,b){ return b.score-a.score; });\n"
    "  var pageGroup=meoFindPageNumberGroup(roots);\n"
    "  var hasPagerUI=(nextCands.length>0)||(loadCands.length>0)||!!pageGroup;\n"
    "  var infinite=meoDetectInfinite(roots, hasPagerUI);\n"
    "  var ranked=[];\n"
    "  // 硬优先级：下一页 > Load More > 页码 > 无限滚动（同分才比 score）\n"
    "  var tier={ nextButton:400, loadMore:300, pageNumbers:200, infiniteScroll:100, none:0 };\n"
    "  if(nextCands.length){\n"
    "    var n=nextCands[0];\n"
    "    var clickEl=n.el;\n"
    "    // 优先点可点击的 a/button\n"
    "    try{\n"
    "      if(clickEl.tagName && clickEl.tagName.toLowerCase()==='li'){\n"
    "        var inner=clickEl.querySelector('a,button');\n"
    "        if(inner) clickEl=inner;\n"
    "      }\n"
    "    }catch(e){}\n"
    "    var prefs=['ul.pagination li.page-next a','.pagination li.page-next a','li.page-next a','.page-next a','.el-pagination .btn-next','button.btn-next','.ant-pagination-next','li.ant-pagination-next button','.pagination .next a','a.next','button.next'];\n"
    "    if(n.preferSel) prefs.unshift(n.preferSel);\n"
    "    ranked.push({\n"
    "      type:'nextButton',\n"
    "      selector:meoStableSelFor(clickEl, prefs),\n"
    "      score:(tier.nextButton + n.score),\n"
    "      reason:'下一页按钮「'+meoNormText(clickEl||n.el).slice(0,12)+'」',\n"
    "      pageDelayMs:800,\n"
    "      maxPages:50\n"
    "    });\n"
    "  }\n"
    "  if(loadCands.length){\n"
    "    var m=loadCands[0];\n"
    "    ranked.push({\n"
    "      type:'loadMore',\n"
    "      selector:meoStableSelFor(m.el, ['.load-more','button.load-more','[class*=\"load-more\"]','[class*=\"loadMore\"]']),\n"
    "      score:tier.loadMore + m.score,\n"
    "      reason:'Load More「'+meoNormText(m.el).slice(0,16)+'」',\n"
    "      pageDelayMs:900,\n"
    "      maxPages:80\n"
    "    });\n"
    "  }\n"
    "  if(pageGroup){\n"
    "    pageGroup.pageDelayMs=800;\n"
    "    pageGroup.maxPages=50;\n"
    "    pageGroup.score=(tier.pageNumbers + (pageGroup.score||0));\n"
    "    ranked.push(pageGroup);\n"
    "  }\n"
    "  if(infinite){\n"
    "    infinite.score=tier.infiniteScroll + (infinite.score||0);\n"
    "    ranked.push(infinite);\n"
    "  }\n"
    "  ranked.sort(function(a,b){ return (b.score||0)-(a.score||0); });\n"
    "  if(!ranked.length){\n"
    "    return { type:'none', selector:'', score:0, reason:'未发现翻页控件' };\n"
    "  }\n"
    "  return ranked[0];\n"
    "}\n";
}

+ (void)detectPaginationInWebView:(WKWebView *)webView
                 nearContainerPath:(NSString *)containerPath
                        completion:(void (^)(NSDictionary *pagination))completion {
    if (!webView) {
        if (completion) {
            completion(@{ @"type": @"none", @"selector": @"", @"score": @0, @"reason": @"无 WebView" });
        }
        return;
    }
    NSString *pathJSON = [self jsonStringLiteral:containerPath ?: @""];
    NSString *js = [NSString stringWithFormat:
                    @"(function(){\n%@\nreturn meoDetectPagination(%@);\n})();",
                    [self paginationHelpersJavaScript], pathJSON];
    [webView evaluateJavaScript:js completionHandler:^(id result, NSError *error) {
        (void)error;
        if ([result isKindOfClass:[NSDictionary class]]) {
            if (completion) completion((NSDictionary *)result);
            return;
        }
        if (completion) {
            completion(@{ @"type": @"none", @"selector": @"", @"score": @0, @"reason": @"翻页检测失败" });
        }
    }];
}

@end
